// Package pdf renders sales and purchase bills as PDF documents using go-pdf/fpdf, a pure-Go
// (no cgo) PDF library. One fixed A4 layout is shared by both bill types via BillData.
package pdf

import (
	"bytes"
	"fmt"

	"github.com/go-pdf/fpdf"
)

type BillItem struct {
	ProductName string
	ProductSKU  string
	Unit        string
	Quantity    float64
	UnitPrice   float64
	LineTotal   float64
	BelowCost   bool
}

type BillData struct {
	DocumentTitle     string // "TAX INVOICE" or "PURCHASE BILL"
	BillNumber        string
	BillDate          string
	CompanyName       string
	CompanyCode       string
	CounterpartyName  string
	CounterpartyPhone string
	CounterpartyArea  string
	Items             []BillItem
	TotalAmount       float64
	AmountPaid        float64
	Status            string // COMPLETED or CANCELLED
	CancelledReason   string
}

func money(v float64) string {
	return fmt.Sprintf("Rs. %.2f", v)
}

// Generate renders a bill to PDF bytes.
func Generate(data BillData) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	pdf.AddPage()

	// Header
	pdf.SetFont("Helvetica", "B", 16)
	pdf.CellFormat(120, 8, data.CompanyName, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 14)
	pdf.CellFormat(65, 8, data.DocumentTitle, "", 1, "R", false, 0, "")

	pdf.SetFont("Helvetica", "", 10)
	pdf.CellFormat(120, 6, "Company Code: "+data.CompanyCode, "", 0, "L", false, 0, "")
	pdf.CellFormat(65, 6, "Bill No: "+data.BillNumber, "", 1, "R", false, 0, "")
	pdf.CellFormat(120, 6, "", "", 0, "L", false, 0, "")
	pdf.CellFormat(65, 6, "Date: "+data.BillDate, "", 1, "R", false, 0, "")

	if data.Status == "CANCELLED" {
		pdf.SetTextColor(178, 58, 52)
		pdf.SetFont("Helvetica", "B", 12)
		pdf.CellFormat(0, 8, "*** CANCELLED ***", "", 1, "C", false, 0, "")
		if data.CancelledReason != "" {
			pdf.SetFont("Helvetica", "", 9)
			pdf.CellFormat(0, 6, "Reason: "+data.CancelledReason, "", 1, "C", false, 0, "")
		}
		pdf.SetTextColor(0, 0, 0)
	}

	pdf.Ln(4)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(0, 6, "Bill To:", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.CellFormat(0, 6, data.CounterpartyName, "", 1, "L", false, 0, "")
	if data.CounterpartyPhone != "" {
		pdf.CellFormat(0, 6, "Phone: "+data.CounterpartyPhone, "", 1, "L", false, 0, "")
	}
	if data.CounterpartyArea != "" {
		pdf.CellFormat(0, 6, data.CounterpartyArea, "", 1, "L", false, 0, "")
	}

	pdf.Ln(6)

	// Item table
	colWidths := []float64{55, 25, 15, 20, 25, 20, 20}
	headers := []string{"Product", "Code", "Unit", "Qty", "Price", "Below", "Total"}
	pdf.SetFillColor(230, 227, 217)
	pdf.SetFont("Helvetica", "B", 9)
	for i, h := range headers {
		align := "L"
		if i >= 3 {
			align = "R"
		}
		pdf.CellFormat(colWidths[i], 8, h, "1", 0, align, true, 0, "")
	}
	pdf.Ln(-1)

	pdf.SetFont("Helvetica", "", 9)
	fill := false
	for _, item := range data.Items {
		if fill {
			pdf.SetFillColor(245, 244, 240)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		below := ""
		if item.BelowCost {
			below = "YES"
		}
		pdf.CellFormat(colWidths[0], 7, truncate(item.ProductName, 30), "1", 0, "L", true, 0, "")
		pdf.CellFormat(colWidths[1], 7, item.ProductSKU, "1", 0, "L", true, 0, "")
		pdf.CellFormat(colWidths[2], 7, item.Unit, "1", 0, "R", true, 0, "")
		pdf.CellFormat(colWidths[3], 7, fmt.Sprintf("%.3f", item.Quantity), "1", 0, "R", true, 0, "")
		pdf.CellFormat(colWidths[4], 7, fmt.Sprintf("%.2f", item.UnitPrice), "1", 0, "R", true, 0, "")
		pdf.CellFormat(colWidths[5], 7, below, "1", 0, "R", true, 0, "")
		pdf.CellFormat(colWidths[6], 7, fmt.Sprintf("%.2f", item.LineTotal), "1", 0, "R", true, 0, "")
		pdf.Ln(-1)
		fill = !fill
	}

	pdf.Ln(4)

	balance := data.TotalAmount - data.AmountPaid
	paymentStatus := "UNPAID"
	if data.AmountPaid >= data.TotalAmount {
		paymentStatus = "PAID"
	} else if data.AmountPaid > 0 {
		paymentStatus = "PARTIAL"
	}

	pdf.SetFont("Helvetica", "", 10)
	writeTotalsRow(pdf, "Total Amount:", money(data.TotalAmount))
	writeTotalsRow(pdf, "Amount Paid:", money(data.AmountPaid))
	writeTotalsRow(pdf, "Balance Due:", money(balance))
	pdf.SetFont("Helvetica", "B", 10)
	writeTotalsRow(pdf, "Payment Status:", paymentStatus)

	pdf.Ln(10)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(107, 114, 128)
	pdf.CellFormat(0, 5, "Generated by RetailApp", "", 1, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func writeTotalsRow(pdf *fpdf.Fpdf, label, value string) {
	pdf.CellFormat(150, 6, label, "", 0, "R", false, 0, "")
	pdf.CellFormat(30, 6, value, "", 1, "R", false, 0, "")
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}
