// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachmentCountsByEntity = `-- name: AttachmentCountsByEntity :many
SELECT entity_id, COUNT(*)::int AS photo_count
FROM transaction_attachments
WHERE company_id = $1 AND entity_type = $2 AND entity_id = ANY($3::int[]) AND deleted_at IS NULL
GROUP BY entity_id
`

type AttachmentCountsByEntityParams struct {
	CompanyID  int32
	EntityType string
	EntityIds  []int32
}

type AttachmentCountsByEntityRow struct {
	EntityID   int32
	PhotoCount int32
}

func (q *Queries) AttachmentCountsByEntity(ctx context.Context, arg AttachmentCountsByEntityParams) ([]AttachmentCountsByEntityRow, error) {
	rows, err := q.db.Query(ctx, attachmentCountsByEntity, arg.CompanyID, arg.EntityType, arg.EntityIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttachmentCountsByEntityRow
	for rows.Next() {
		var i AttachmentCountsByEntityRow
		if err := rows.Scan(&i.EntityID, &i.PhotoCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAttachments = `-- name: CountAttachments :one
SELECT COUNT(*)::int FROM transaction_attachments
WHERE company_id = $1 AND entity_type = $2 AND entity_id = $3 AND deleted_at IS NULL
`

type CountAttachmentsParams struct {
	CompanyID  int32
	EntityType string
	EntityID   int32
}

func (q *Queries) CountAttachments(ctx context.Context, arg CountAttachmentsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAttachments, arg.CompanyID, arg.EntityType, arg.EntityID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO transaction_attachments (company_id, entity_type, entity_id, file_path, content_type, size_bytes, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, entity_type, entity_id, file_path, content_type, size_bytes, uploaded_by, created_at, deleted_at, deleted_by, delete_reason
`

type CreateAttachmentParams struct {
	CompanyID   int32
	EntityType  string
	EntityID    int32
	FilePath    string
	ContentType string
	SizeBytes   int32
	UploadedBy  pgtype.Int4
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (TransactionAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.CompanyID,
		arg.EntityType,
		arg.EntityID,
		arg.FilePath,
		arg.ContentType,
		arg.SizeBytes,
		arg.UploadedBy,
	)
	var i TransactionAttachment
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EntityType,
		&i.EntityID,
		&i.FilePath,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, company_id, entity_type, entity_id, file_path, content_type, size_bytes, uploaded_by, created_at, deleted_at, deleted_by, delete_reason FROM transaction_attachments
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type GetAttachmentParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (TransactionAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, arg.ID, arg.CompanyID)
	var i TransactionAttachment
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EntityType,
		&i.EntityID,
		&i.FilePath,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeleteReason,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT a.id, a.entity_type, a.entity_id, a.content_type, a.size_bytes, a.created_at,
       COALESCE(u.name, '')::text AS uploaded_by_name
FROM transaction_attachments a
LEFT JOIN users u ON u.id = a.uploaded_by
WHERE a.company_id = $1 AND a.entity_type = $2 AND a.entity_id = $3 AND a.deleted_at IS NULL
ORDER BY a.created_at, a.id
`

type ListAttachmentsParams struct {
	CompanyID  int32
	EntityType string
	EntityID   int32
}

type ListAttachmentsRow struct {
	ID             int32
	EntityType     string
	EntityID       int32
	ContentType    string
	SizeBytes      int32
	CreatedAt      pgtype.Timestamptz
	UploadedByName string
}

func (q *Queries) ListAttachments(ctx context.Context, arg ListAttachmentsParams) ([]ListAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listAttachments, arg.CompanyID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsRow
	for rows.Next() {
		var i ListAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAttachment = `-- name: SoftDeleteAttachment :execrows
UPDATE transaction_attachments
SET deleted_at = now(), deleted_by = $3, delete_reason = $4
WHERE id = $1 AND company_id = $2 AND deleted_at IS NULL
`

type SoftDeleteAttachmentParams struct {
	ID           int32
	CompanyID    int32
	DeletedBy    pgtype.Int4
	DeleteReason pgtype.Text
}

func (q *Queries) SoftDeleteAttachment(ctx context.Context, arg SoftDeleteAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAttachment,
		arg.ID,
		arg.CompanyID,
		arg.DeletedBy,
		arg.DeleteReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
