// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLogEntry = `-- name: CreateAuditLogEntry :one
INSERT INTO audit_log (company_id, actor_user_id, action, entity_type, entity_id, reason, reversal_txn_id, inventory_impact, payment_impact)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, company_id, actor_user_id, action, entity_type, entity_id, reason, reversal_txn_id, inventory_impact, payment_impact, created_at
`

type CreateAuditLogEntryParams struct {
	CompanyID       pgtype.Int4
	ActorUserID     pgtype.Int4
	Action          string
	EntityType      string
	EntityID        int32
	Reason          pgtype.Text
	ReversalTxnID   pgtype.Int4
	InventoryImpact []byte
	PaymentImpact   []byte
}

func (q *Queries) CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLogEntry,
		arg.CompanyID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Reason,
		arg.ReversalTxnID,
		arg.InventoryImpact,
		arg.PaymentImpact,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Reason,
		&i.ReversalTxnID,
		&i.InventoryImpact,
		&i.PaymentImpact,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogByEntity = `-- name: ListAuditLogByEntity :many
SELECT id, company_id, actor_user_id, action, entity_type, entity_id, reason, reversal_txn_id, inventory_impact, payment_impact, created_at FROM audit_log WHERE entity_type = $1 AND entity_id = $2 ORDER BY created_at DESC
`

type ListAuditLogByEntityParams struct {
	EntityType string
	EntityID   int32
}

func (q *Queries) ListAuditLogByEntity(ctx context.Context, arg ListAuditLogByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Reason,
			&i.ReversalTxnID,
			&i.InventoryImpact,
			&i.PaymentImpact,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
