// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bill_sequences.sql

package db

import (
	"context"
)

const nextBillNumber = `-- name: NextBillNumber :one
INSERT INTO bill_sequences (company_id, bill_type, next_number)
VALUES ($1, $2, 1)
ON CONFLICT (company_id, bill_type) DO UPDATE SET next_number = bill_sequences.next_number + 1
RETURNING next_number
`

type NextBillNumberParams struct {
	CompanyID int32
	BillType  string
}

func (q *Queries) NextBillNumber(ctx context.Context, arg NextBillNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextBillNumber, arg.CompanyID, arg.BillType)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}
