// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (company_id, name)
VALUES ($1, $2)
RETURNING id, company_id, name, created_at
`

type CreateCategoryParams struct {
	CompanyID int32
	Name      string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.CompanyID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createSubcategory = `-- name: CreateSubcategory :one
INSERT INTO subcategories (company_id, category_id, name)
VALUES ($1, $2, $3)
RETURNING id, company_id, category_id, name, created_at
`

type CreateSubcategoryParams struct {
	CompanyID  int32
	CategoryID int32
	Name       string
}

func (q *Queries) CreateSubcategory(ctx context.Context, arg CreateSubcategoryParams) (Subcategory, error) {
	row := q.db.QueryRow(ctx, createSubcategory, arg.CompanyID, arg.CategoryID, arg.Name)
	var i Subcategory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CategoryID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, company_id, name, created_at FROM categories WHERE id = $1 AND company_id = $2
`

type GetCategoryParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.CompanyID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSubcategory = `-- name: GetSubcategory :one
SELECT id, company_id, category_id, name, created_at FROM subcategories WHERE id = $1 AND company_id = $2
`

type GetSubcategoryParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) GetSubcategory(ctx context.Context, arg GetSubcategoryParams) (Subcategory, error) {
	row := q.db.QueryRow(ctx, getSubcategory, arg.ID, arg.CompanyID)
	var i Subcategory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CategoryID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, company_id, name, created_at FROM categories WHERE company_id = $1 ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context, companyID int32) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubcategories = `-- name: ListSubcategories :many
SELECT id, company_id, category_id, name, created_at FROM subcategories WHERE company_id = $1 AND category_id = $2 ORDER BY name
`

type ListSubcategoriesParams struct {
	CompanyID  int32
	CategoryID int32
}

func (q *Queries) ListSubcategories(ctx context.Context, arg ListSubcategoriesParams) ([]Subcategory, error) {
	rows, err := q.db.Query(ctx, listSubcategories, arg.CompanyID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subcategory
	for rows.Next() {
		var i Subcategory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CategoryID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
