// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (company_name, company_code, joining_date, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, company_name, company_code, status, joining_date, created_on, modified_on, created_by, modified_by, version
`

type CreateCompanyParams struct {
	CompanyName string
	CompanyCode string
	JoiningDate pgtype.Date
	CreatedBy   pgtype.Int4
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.CompanyName,
		arg.CompanyCode,
		arg.JoiningDate,
		arg.CreatedBy,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyCode,
		&i.Status,
		&i.JoiningDate,
		&i.CreatedOn,
		&i.ModifiedOn,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.Version,
	)
	return i, err
}

const getCompanyByCode = `-- name: GetCompanyByCode :one
SELECT id, company_name, company_code, status, joining_date, created_on, modified_on, created_by, modified_by, version FROM companies WHERE company_code = $1
`

func (q *Queries) GetCompanyByCode(ctx context.Context, companyCode string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByCode, companyCode)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyCode,
		&i.Status,
		&i.JoiningDate,
		&i.CreatedOn,
		&i.ModifiedOn,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.Version,
	)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, company_name, company_code, status, joining_date, created_on, modified_on, created_by, modified_by, version FROM companies WHERE id = $1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id int32) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyCode,
		&i.Status,
		&i.JoiningDate,
		&i.CreatedOn,
		&i.ModifiedOn,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.Version,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, company_name, company_code, status, joining_date, created_on, modified_on, created_by, modified_by, version FROM companies ORDER BY joining_date DESC
`

func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.CompanyCode,
			&i.Status,
			&i.JoiningDate,
			&i.CreatedOn,
			&i.ModifiedOn,
			&i.CreatedBy,
			&i.ModifiedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanyStatus = `-- name: UpdateCompanyStatus :one
UPDATE companies SET status = $2, modified_on = now(), modified_by = $3 WHERE id = $1
RETURNING id, company_name, company_code, status, joining_date, created_on, modified_on, created_by, modified_by, version
`

type UpdateCompanyStatusParams struct {
	ID         int32
	Status     string
	ModifiedBy pgtype.Int4
}

func (q *Queries) UpdateCompanyStatus(ctx context.Context, arg UpdateCompanyStatusParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompanyStatus, arg.ID, arg.Status, arg.ModifiedBy)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyCode,
		&i.Status,
		&i.JoiningDate,
		&i.CreatedOn,
		&i.ModifiedOn,
		&i.CreatedBy,
		&i.ModifiedBy,
		&i.Version,
	)
	return i, err
}
