// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cost_layers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelCostLayer = `-- name: CancelCostLayer :exec
UPDATE product_cost_layers SET status = 'CANCELLED', quantity_remaining = 0 WHERE id = $1
`

func (q *Queries) CancelCostLayer(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, cancelCostLayer, id)
	return err
}

const consumeCostLayer = `-- name: ConsumeCostLayer :exec
UPDATE product_cost_layers
SET quantity_remaining = quantity_remaining - $2,
    status = CASE WHEN quantity_remaining - $2 <= 0 THEN 'DEPLETED' ELSE status END
WHERE id = $1
`

type ConsumeCostLayerParams struct {
	ID                int32
	QuantityRemaining pgtype.Numeric
}

func (q *Queries) ConsumeCostLayer(ctx context.Context, arg ConsumeCostLayerParams) error {
	_, err := q.db.Exec(ctx, consumeCostLayer, arg.ID, arg.QuantityRemaining)
	return err
}

const createCostLayer = `-- name: CreateCostLayer :one
INSERT INTO product_cost_layers (company_id, product_id, purchase_bill_item_id, buying_price, quantity_received, quantity_remaining, created_by)
VALUES ($1, $2, $3, $4, $5, $5, $6)
RETURNING id, company_id, product_id, purchase_bill_item_id, buying_price, quantity_received, quantity_remaining, created_on, created_by, status
`

type CreateCostLayerParams struct {
	CompanyID          int32
	ProductID          int32
	PurchaseBillItemID int32
	BuyingPrice        pgtype.Numeric
	QuantityReceived   pgtype.Numeric
	CreatedBy          pgtype.Int4
}

func (q *Queries) CreateCostLayer(ctx context.Context, arg CreateCostLayerParams) (ProductCostLayer, error) {
	row := q.db.QueryRow(ctx, createCostLayer,
		arg.CompanyID,
		arg.ProductID,
		arg.PurchaseBillItemID,
		arg.BuyingPrice,
		arg.QuantityReceived,
		arg.CreatedBy,
	)
	var i ProductCostLayer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ProductID,
		&i.PurchaseBillItemID,
		&i.BuyingPrice,
		&i.QuantityReceived,
		&i.QuantityRemaining,
		&i.CreatedOn,
		&i.CreatedBy,
		&i.Status,
	)
	return i, err
}

const createSaleItemCostConsumption = `-- name: CreateSaleItemCostConsumption :one
INSERT INTO sale_item_cost_consumptions (sale_item_id, product_cost_layer_id, quantity, unit_cost)
VALUES ($1, $2, $3, $4)
RETURNING id, sale_item_id, product_cost_layer_id, quantity, unit_cost
`

type CreateSaleItemCostConsumptionParams struct {
	SaleItemID         int32
	ProductCostLayerID int32
	Quantity           pgtype.Numeric
	UnitCost           pgtype.Numeric
}

func (q *Queries) CreateSaleItemCostConsumption(ctx context.Context, arg CreateSaleItemCostConsumptionParams) (SaleItemCostConsumption, error) {
	row := q.db.QueryRow(ctx, createSaleItemCostConsumption,
		arg.SaleItemID,
		arg.ProductCostLayerID,
		arg.Quantity,
		arg.UnitCost,
	)
	var i SaleItemCostConsumption
	err := row.Scan(
		&i.ID,
		&i.SaleItemID,
		&i.ProductCostLayerID,
		&i.Quantity,
		&i.UnitCost,
	)
	return i, err
}

const getCostLayerByPurchaseItem = `-- name: GetCostLayerByPurchaseItem :one
SELECT id, company_id, product_id, purchase_bill_item_id, buying_price, quantity_received, quantity_remaining, created_on, created_by, status FROM product_cost_layers WHERE purchase_bill_item_id = $1
`

func (q *Queries) GetCostLayerByPurchaseItem(ctx context.Context, purchaseBillItemID int32) (ProductCostLayer, error) {
	row := q.db.QueryRow(ctx, getCostLayerByPurchaseItem, purchaseBillItemID)
	var i ProductCostLayer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ProductID,
		&i.PurchaseBillItemID,
		&i.BuyingPrice,
		&i.QuantityReceived,
		&i.QuantityRemaining,
		&i.CreatedOn,
		&i.CreatedBy,
		&i.Status,
	)
	return i, err
}

const listActiveCostLayersForUpdate = `-- name: ListActiveCostLayersForUpdate :many
SELECT id, company_id, product_id, purchase_bill_item_id, buying_price, quantity_received, quantity_remaining, created_on, created_by, status FROM product_cost_layers
WHERE company_id = $1 AND product_id = $2 AND status = 'ACTIVE' AND quantity_remaining > 0
ORDER BY created_on ASC
FOR UPDATE
`

type ListActiveCostLayersForUpdateParams struct {
	CompanyID int32
	ProductID int32
}

func (q *Queries) ListActiveCostLayersForUpdate(ctx context.Context, arg ListActiveCostLayersForUpdateParams) ([]ProductCostLayer, error) {
	rows, err := q.db.Query(ctx, listActiveCostLayersForUpdate, arg.CompanyID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCostLayer
	for rows.Next() {
		var i ProductCostLayer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ProductID,
			&i.PurchaseBillItemID,
			&i.BuyingPrice,
			&i.QuantityReceived,
			&i.QuantityRemaining,
			&i.CreatedOn,
			&i.CreatedBy,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostConsumptionsBySale = `-- name: ListCostConsumptionsBySale :many
SELECT sicc.id, sicc.sale_item_id, sicc.product_cost_layer_id, sicc.quantity, sicc.unit_cost FROM sale_item_cost_consumptions sicc
JOIN sale_items si ON si.id = sicc.sale_item_id
WHERE si.sale_id = $1
`

func (q *Queries) ListCostConsumptionsBySale(ctx context.Context, saleID int32) ([]SaleItemCostConsumption, error) {
	rows, err := q.db.Query(ctx, listCostConsumptionsBySale, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleItemCostConsumption
	for rows.Next() {
		var i SaleItemCostConsumption
		if err := rows.Scan(
			&i.ID,
			&i.SaleItemID,
			&i.ProductCostLayerID,
			&i.Quantity,
			&i.UnitCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreCostLayer = `-- name: RestoreCostLayer :exec
UPDATE product_cost_layers
SET quantity_remaining = quantity_remaining + $2,
    status = CASE WHEN status = 'DEPLETED' AND quantity_remaining + $2 > 0 THEN 'ACTIVE' ELSE status END
WHERE id = $1
`

type RestoreCostLayerParams struct {
	ID                int32
	QuantityRemaining pgtype.Numeric
}

func (q *Queries) RestoreCostLayer(ctx context.Context, arg RestoreCostLayerParams) error {
	_, err := q.db.Exec(ctx, restoreCostLayer, arg.ID, arg.QuantityRemaining)
	return err
}
