// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: factories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFactory = `-- name: CreateFactory :one
INSERT INTO factories (company_id, name, contact_person, primary_phone, secondary_phone, address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, name, contact_person, primary_phone, secondary_phone, address, created_at
`

type CreateFactoryParams struct {
	CompanyID      int32
	Name           string
	ContactPerson  pgtype.Text
	PrimaryPhone   string
	SecondaryPhone pgtype.Text
	Address        pgtype.Text
}

func (q *Queries) CreateFactory(ctx context.Context, arg CreateFactoryParams) (Factory, error) {
	row := q.db.QueryRow(ctx, createFactory,
		arg.CompanyID,
		arg.Name,
		arg.ContactPerson,
		arg.PrimaryPhone,
		arg.SecondaryPhone,
		arg.Address,
	)
	var i Factory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ContactPerson,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFactory = `-- name: DeleteFactory :exec
DELETE FROM factories WHERE id = $1 AND company_id = $2
`

type DeleteFactoryParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) DeleteFactory(ctx context.Context, arg DeleteFactoryParams) error {
	_, err := q.db.Exec(ctx, deleteFactory, arg.ID, arg.CompanyID)
	return err
}

const getFactory = `-- name: GetFactory :one
SELECT id, company_id, name, contact_person, primary_phone, secondary_phone, address, created_at FROM factories WHERE id = $1 AND company_id = $2
`

type GetFactoryParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) GetFactory(ctx context.Context, arg GetFactoryParams) (Factory, error) {
	row := q.db.QueryRow(ctx, getFactory, arg.ID, arg.CompanyID)
	var i Factory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ContactPerson,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const listFactories = `-- name: ListFactories :many
SELECT id, company_id, name, contact_person, primary_phone, secondary_phone, address, created_at FROM factories WHERE company_id = $1 ORDER BY name
`

func (q *Queries) ListFactories(ctx context.Context, companyID int32) ([]Factory, error) {
	rows, err := q.db.Query(ctx, listFactories, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Factory
	for rows.Next() {
		var i Factory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.ContactPerson,
			&i.PrimaryPhone,
			&i.SecondaryPhone,
			&i.Address,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFactory = `-- name: UpdateFactory :one
UPDATE factories
SET name = $3, contact_person = $4, primary_phone = $5, secondary_phone = $6, address = $7
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, contact_person, primary_phone, secondary_phone, address, created_at
`

type UpdateFactoryParams struct {
	ID             int32
	CompanyID      int32
	Name           string
	ContactPerson  pgtype.Text
	PrimaryPhone   string
	SecondaryPhone pgtype.Text
	Address        pgtype.Text
}

func (q *Queries) UpdateFactory(ctx context.Context, arg UpdateFactoryParams) (Factory, error) {
	row := q.db.QueryRow(ctx, updateFactory,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.ContactPerson,
		arg.PrimaryPhone,
		arg.SecondaryPhone,
		arg.Address,
	)
	var i Factory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ContactPerson,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}
