// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: factories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveFactory = `-- name: ArchiveFactory :one
UPDATE factories SET archived_at = now(), archived_by = $3
WHERE id = $1 AND company_id = $2 AND archived_at IS NULL
RETURNING id, company_id, name, contact_person, primary_phone, secondary_phone, address, created_at, archived_at, archived_by
`

type ArchiveFactoryParams struct {
	ID         int32
	CompanyID  int32
	ArchivedBy pgtype.Int4
}

// Cycle 5: soft delete. Old bills, payments and ledgers keep pointing at the row.
func (q *Queries) ArchiveFactory(ctx context.Context, arg ArchiveFactoryParams) (Factory, error) {
	row := q.db.QueryRow(ctx, archiveFactory, arg.ID, arg.CompanyID, arg.ArchivedBy)
	var i Factory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ContactPerson,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.Address,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const createFactory = `-- name: CreateFactory :one
INSERT INTO factories (company_id, name, contact_person, primary_phone, secondary_phone, address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, name, contact_person, primary_phone, secondary_phone, address, created_at, archived_at, archived_by
`

type CreateFactoryParams struct {
	CompanyID      int32
	Name           string
	ContactPerson  pgtype.Text
	PrimaryPhone   string
	SecondaryPhone pgtype.Text
	Address        pgtype.Text
}

func (q *Queries) CreateFactory(ctx context.Context, arg CreateFactoryParams) (Factory, error) {
	row := q.db.QueryRow(ctx, createFactory,
		arg.CompanyID,
		arg.Name,
		arg.ContactPerson,
		arg.PrimaryPhone,
		arg.SecondaryPhone,
		arg.Address,
	)
	var i Factory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ContactPerson,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.Address,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const getFactory = `-- name: GetFactory :one
SELECT id, company_id, name, contact_person, primary_phone, secondary_phone, address, created_at, archived_at, archived_by FROM factories WHERE id = $1 AND company_id = $2
`

type GetFactoryParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) GetFactory(ctx context.Context, arg GetFactoryParams) (Factory, error) {
	row := q.db.QueryRow(ctx, getFactory, arg.ID, arg.CompanyID)
	var i Factory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ContactPerson,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.Address,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const listFactories = `-- name: ListFactories :many
SELECT id, company_id, name, contact_person, primary_phone, secondary_phone, address, created_at, archived_at, archived_by FROM factories WHERE company_id = $1 AND archived_at IS NULL ORDER BY name
`

// Active (non-archived) only: what lists, pickers and new bills may use (Cycle 5).
func (q *Queries) ListFactories(ctx context.Context, companyID int32) ([]Factory, error) {
	rows, err := q.db.Query(ctx, listFactories, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Factory
	for rows.Next() {
		var i Factory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.ContactPerson,
			&i.PrimaryPhone,
			&i.SecondaryPhone,
			&i.Address,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.ArchivedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactoriesIncludingArchived = `-- name: ListFactoriesIncludingArchived :many
SELECT id, company_id, name, contact_person, primary_phone, secondary_phone, address, created_at, archived_at, archived_by FROM factories WHERE company_id = $1 ORDER BY archived_at IS NOT NULL, name
`

func (q *Queries) ListFactoriesIncludingArchived(ctx context.Context, companyID int32) ([]Factory, error) {
	rows, err := q.db.Query(ctx, listFactoriesIncludingArchived, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Factory
	for rows.Next() {
		var i Factory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.ContactPerson,
			&i.PrimaryPhone,
			&i.SecondaryPhone,
			&i.Address,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.ArchivedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreFactory = `-- name: RestoreFactory :one
UPDATE factories SET archived_at = NULL, archived_by = NULL
WHERE id = $1 AND company_id = $2 AND archived_at IS NOT NULL
RETURNING id, company_id, name, contact_person, primary_phone, secondary_phone, address, created_at, archived_at, archived_by
`

type RestoreFactoryParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) RestoreFactory(ctx context.Context, arg RestoreFactoryParams) (Factory, error) {
	row := q.db.QueryRow(ctx, restoreFactory, arg.ID, arg.CompanyID)
	var i Factory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ContactPerson,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.Address,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const updateFactory = `-- name: UpdateFactory :one
UPDATE factories
SET name = $3, contact_person = $4, primary_phone = $5, secondary_phone = $6, address = $7
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, contact_person, primary_phone, secondary_phone, address, created_at, archived_at, archived_by
`

type UpdateFactoryParams struct {
	ID             int32
	CompanyID      int32
	Name           string
	ContactPerson  pgtype.Text
	PrimaryPhone   string
	SecondaryPhone pgtype.Text
	Address        pgtype.Text
}

func (q *Queries) UpdateFactory(ctx context.Context, arg UpdateFactoryParams) (Factory, error) {
	row := q.db.QueryRow(ctx, updateFactory,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.ContactPerson,
		arg.PrimaryPhone,
		arg.SecondaryPhone,
		arg.Address,
	)
	var i Factory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.ContactPerson,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.Address,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}
