// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: factories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFactory = `-- name: CreateFactory :one
INSERT INTO factories (name, contact_person, phone, address)
VALUES ($1, $2, $3, $4)
RETURNING id, name, contact_person, phone, address, created_at
`

type CreateFactoryParams struct {
	Name          string
	ContactPerson pgtype.Text
	Phone         pgtype.Text
	Address       pgtype.Text
}

func (q *Queries) CreateFactory(ctx context.Context, arg CreateFactoryParams) (Factory, error) {
	row := q.db.QueryRow(ctx, createFactory,
		arg.Name,
		arg.ContactPerson,
		arg.Phone,
		arg.Address,
	)
	var i Factory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactPerson,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFactory = `-- name: DeleteFactory :exec
DELETE FROM factories WHERE id = $1
`

func (q *Queries) DeleteFactory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFactory, id)
	return err
}

const getFactory = `-- name: GetFactory :one
SELECT id, name, contact_person, phone, address, created_at FROM factories WHERE id = $1
`

func (q *Queries) GetFactory(ctx context.Context, id int32) (Factory, error) {
	row := q.db.QueryRow(ctx, getFactory, id)
	var i Factory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactPerson,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const listFactories = `-- name: ListFactories :many
SELECT id, name, contact_person, phone, address, created_at FROM factories ORDER BY name
`

func (q *Queries) ListFactories(ctx context.Context) ([]Factory, error) {
	rows, err := q.db.Query(ctx, listFactories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Factory
	for rows.Next() {
		var i Factory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactPerson,
			&i.Phone,
			&i.Address,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFactory = `-- name: UpdateFactory :one
UPDATE factories
SET name = $2, contact_person = $3, phone = $4, address = $5
WHERE id = $1
RETURNING id, name, contact_person, phone, address, created_at
`

type UpdateFactoryParams struct {
	ID            int32
	Name          string
	ContactPerson pgtype.Text
	Phone         pgtype.Text
	Address       pgtype.Text
}

func (q *Queries) UpdateFactory(ctx context.Context, arg UpdateFactoryParams) (Factory, error) {
	row := q.db.QueryRow(ctx, updateFactory,
		arg.ID,
		arg.Name,
		arg.ContactPerson,
		arg.Phone,
		arg.Address,
	)
	var i Factory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactPerson,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}
