// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPinnedProducts = `-- name: CountPinnedProducts :one
SELECT COUNT(*)::int FROM products WHERE company_id = $1 AND pinned
`

func (q *Queries) CountPinnedProducts(ctx context.Context, companyID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countPinnedProducts, companyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const customerDues = `-- name: CustomerDues :many
SELECT
  s.id,
  s.name,
  s.primary_phone,
  s.area,
  (
    COALESCE(s.opening_balance, 0)
    + COALESCE(sa.total, 0)
    - COALESCE(sa.paid, 0)
    - COALESCE(pa.paid, 0)
  )::numeric(12,2) AS balance,
  sa.last_at::timestamptz AS last_sale_at,
  pa.last_at::timestamptz AS last_payment_at
FROM shops s
LEFT JOIN (
  SELECT shop_id, SUM(total_amount) AS total, SUM(amount_paid) AS paid, MAX(created_at) AS last_at
  FROM sales WHERE sales.company_id = $1 AND status = 'COMPLETED' GROUP BY shop_id
) sa ON sa.shop_id = s.id
LEFT JOIN (
  SELECT party_id, SUM(amount) AS paid, MAX(created_at) AS last_at
  FROM payments WHERE payments.company_id = $1 AND party_type = 'shop' GROUP BY party_id
) pa ON pa.party_id = s.id
WHERE s.company_id = $1
`

type CustomerDuesRow struct {
	ID            int32
	Name          string
	PrimaryPhone  string
	Area          pgtype.Text
	Balance       pgtype.Numeric
	LastSaleAt    pgtype.Timestamptz
	LastPaymentAt pgtype.Timestamptz
}

// Same balance formula as ShopBalance/ShopDues, plus the timestamps the Android dues list
// sorts on (most recent activity first).
func (q *Queries) CustomerDues(ctx context.Context, companyID int32) ([]CustomerDuesRow, error) {
	rows, err := q.db.Query(ctx, customerDues, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerDuesRow
	for rows.Next() {
		var i CustomerDuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PrimaryPhone,
			&i.Area,
			&i.Balance,
			&i.LastSaleAt,
			&i.LastPaymentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const customerUsualProducts = `-- name: CustomerUsualProducts :many
WITH recent AS (
  SELECT sales.id FROM sales
  WHERE sales.company_id = $1 AND sales.shop_id = $2 AND sales.status = 'COMPLETED'
  ORDER BY sales.created_at DESC
  LIMIT 10
)
SELECT p.id, p.name, p.sku, p.unit, p.current_selling_price, p.current_stock, p.pinned,
       COUNT(si.id)::int AS uses
FROM sale_items si
JOIN recent r ON r.id = si.sale_id
JOIN products p ON p.id = si.product_id
GROUP BY p.id
ORDER BY uses DESC, p.name
LIMIT $3
`

type CustomerUsualProductsParams struct {
	CompanyID int32
	ShopID    int32
	Limit     int32
}

type CustomerUsualProductsRow struct {
	ID                  int32
	Name                string
	Sku                 string
	Unit                string
	CurrentSellingPrice pgtype.Numeric
	CurrentStock        pgtype.Numeric
	Pinned              bool
	Uses                int32
}

// Usually buys: a customer's most frequent items across their last 10 completed sales.
func (q *Queries) CustomerUsualProducts(ctx context.Context, arg CustomerUsualProductsParams) ([]CustomerUsualProductsRow, error) {
	rows, err := q.db.Query(ctx, customerUsualProducts, arg.CompanyID, arg.ShopID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerUsualProductsRow
	for rows.Next() {
		var i CustomerUsualProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Unit,
			&i.CurrentSellingPrice,
			&i.CurrentStock,
			&i.Pinned,
			&i.Uses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const frequentPurchaseProducts = `-- name: FrequentPurchaseProducts :many
WITH usage AS (
  SELECT pi.product_id, COUNT(*) AS uses, MAX(pu.created_at) AS last_used
  FROM purchase_items pi
  JOIN purchases pu ON pu.id = pi.purchase_id
  WHERE pu.company_id = $1 AND pu.status = 'COMPLETED' AND pu.purchase_date >= CURRENT_DATE - 90
  GROUP BY pi.product_id
)
SELECT p.id, p.name, p.sku, p.unit, p.current_selling_price, p.current_stock, p.pinned,
       COALESCE(u.uses, 0)::int AS uses
FROM products p
LEFT JOIN usage u ON u.product_id = p.id
WHERE p.company_id = $1 AND (p.pinned OR u.uses IS NOT NULL)
ORDER BY p.pinned DESC, u.uses DESC NULLS LAST, u.last_used DESC NULLS LAST, p.name
LIMIT $2
`

type FrequentPurchaseProductsParams struct {
	CompanyID int32
	Limit     int32
}

type FrequentPurchaseProductsRow struct {
	ID                  int32
	Name                string
	Sku                 string
	Unit                string
	CurrentSellingPrice pgtype.Numeric
	CurrentStock        pgtype.Numeric
	Pinned              bool
	Uses                int32
}

func (q *Queries) FrequentPurchaseProducts(ctx context.Context, arg FrequentPurchaseProductsParams) ([]FrequentPurchaseProductsRow, error) {
	rows, err := q.db.Query(ctx, frequentPurchaseProducts, arg.CompanyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FrequentPurchaseProductsRow
	for rows.Next() {
		var i FrequentPurchaseProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Unit,
			&i.CurrentSellingPrice,
			&i.CurrentStock,
			&i.Pinned,
			&i.Uses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const frequentSaleProducts = `-- name: FrequentSaleProducts :many
WITH usage AS (
  SELECT si.product_id, COUNT(*) AS uses, MAX(s.created_at) AS last_used
  FROM sale_items si
  JOIN sales s ON s.id = si.sale_id
  WHERE s.company_id = $1 AND s.status = 'COMPLETED' AND s.sale_date >= CURRENT_DATE - 90
  GROUP BY si.product_id
)
SELECT p.id, p.name, p.sku, p.unit, p.current_selling_price, p.current_stock, p.pinned,
       COALESCE(u.uses, 0)::int AS uses
FROM products p
LEFT JOIN usage u ON u.product_id = p.id
WHERE p.company_id = $1 AND (p.pinned OR u.uses IS NOT NULL)
ORDER BY p.pinned DESC, u.uses DESC NULLS LAST, u.last_used DESC NULLS LAST, p.name
LIMIT $2
`

type FrequentSaleProductsParams struct {
	CompanyID int32
	Limit     int32
}

type FrequentSaleProductsRow struct {
	ID                  int32
	Name                string
	Sku                 string
	Unit                string
	CurrentSellingPrice pgtype.Numeric
	CurrentStock        pgtype.Numeric
	Pinned              bool
	Uses                int32
}

// Pinned products first, then the products on the most non-cancelled sale bill lines in the
// last 90 days, most recently used breaking ties.
func (q *Queries) FrequentSaleProducts(ctx context.Context, arg FrequentSaleProductsParams) ([]FrequentSaleProductsRow, error) {
	rows, err := q.db.Query(ctx, frequentSaleProducts, arg.CompanyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FrequentSaleProductsRow
	for rows.Next() {
		var i FrequentSaleProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Unit,
			&i.CurrentSellingPrice,
			&i.CurrentStock,
			&i.Pinned,
			&i.Uses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPayment = `-- name: GetPayment :one
SELECT id, company_id, party_type, party_id, amount, payment_mode, payment_date, notes, created_by, created_at FROM payments WHERE id = $1 AND company_id = $2
`

type GetPaymentParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, arg.ID, arg.CompanyID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PartyType,
		&i.PartyID,
		&i.Amount,
		&i.PaymentMode,
		&i.PaymentDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPurchasesByFactory = `-- name: ListPurchasesByFactory :many
SELECT p.id, p.bill_number, p.invoice_no, p.purchase_date, p.total_amount, p.amount_paid, p.status, p.created_at,
       (SELECT COUNT(*) FROM purchase_items pi WHERE pi.purchase_id = p.id)::int AS item_count
FROM purchases p
WHERE p.company_id = $1 AND p.factory_id = $2
ORDER BY p.purchase_date, p.created_at, p.id
`

type ListPurchasesByFactoryParams struct {
	CompanyID int32
	FactoryID int32
}

type ListPurchasesByFactoryRow struct {
	ID           int32
	BillNumber   string
	InvoiceNo    pgtype.Text
	PurchaseDate pgtype.Date
	TotalAmount  pgtype.Numeric
	AmountPaid   pgtype.Numeric
	Status       string
	CreatedAt    pgtype.Timestamptz
	ItemCount    int32
}

func (q *Queries) ListPurchasesByFactory(ctx context.Context, arg ListPurchasesByFactoryParams) ([]ListPurchasesByFactoryRow, error) {
	rows, err := q.db.Query(ctx, listPurchasesByFactory, arg.CompanyID, arg.FactoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchasesByFactoryRow
	for rows.Next() {
		var i ListPurchasesByFactoryRow
		if err := rows.Scan(
			&i.ID,
			&i.BillNumber,
			&i.InvoiceNo,
			&i.PurchaseDate,
			&i.TotalAmount,
			&i.AmountPaid,
			&i.Status,
			&i.CreatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesByShop = `-- name: ListSalesByShop :many
SELECT s.id, s.bill_number, s.sale_date, s.total_amount, s.amount_paid, s.status, s.created_at,
       (SELECT COUNT(*) FROM sale_items si WHERE si.sale_id = s.id)::int AS item_count
FROM sales s
WHERE s.company_id = $1 AND s.shop_id = $2
ORDER BY s.sale_date, s.created_at, s.id
`

type ListSalesByShopParams struct {
	CompanyID int32
	ShopID    int32
}

type ListSalesByShopRow struct {
	ID          int32
	BillNumber  string
	SaleDate    pgtype.Date
	TotalAmount pgtype.Numeric
	AmountPaid  pgtype.Numeric
	Status      string
	CreatedAt   pgtype.Timestamptz
	ItemCount   int32
}

func (q *Queries) ListSalesByShop(ctx context.Context, arg ListSalesByShopParams) ([]ListSalesByShopRow, error) {
	rows, err := q.db.Query(ctx, listSalesByShop, arg.CompanyID, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesByShopRow
	for rows.Next() {
		var i ListSalesByShopRow
		if err := rows.Scan(
			&i.ID,
			&i.BillNumber,
			&i.SaleDate,
			&i.TotalAmount,
			&i.AmountPaid,
			&i.Status,
			&i.CreatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductPinned = `-- name: SetProductPinned :execrows
UPDATE products SET pinned = $3 WHERE id = $1 AND company_id = $2
`

type SetProductPinnedParams struct {
	ID        int32
	CompanyID int32
	Pinned    bool
}

func (q *Queries) SetProductPinned(ctx context.Context, arg SetProductPinnedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProductPinned, arg.ID, arg.CompanyID, arg.Pinned)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supplierDues = `-- name: SupplierDues :many
SELECT
  f.id,
  f.name,
  f.primary_phone,
  f.address AS area,
  (
    COALESCE(pu.total, 0)
    - COALESCE(pu.paid, 0)
    - COALESCE(pa.paid, 0)
  )::numeric(12,2) AS balance,
  pu.last_at::timestamptz AS last_purchase_at,
  pa.last_at::timestamptz AS last_payment_at
FROM factories f
LEFT JOIN (
  SELECT factory_id, SUM(total_amount) AS total, SUM(amount_paid) AS paid, MAX(created_at) AS last_at
  FROM purchases WHERE purchases.company_id = $1 AND status = 'COMPLETED' GROUP BY factory_id
) pu ON pu.factory_id = f.id
LEFT JOIN (
  SELECT party_id, SUM(amount) AS paid, MAX(created_at) AS last_at
  FROM payments WHERE payments.company_id = $1 AND party_type = 'factory' GROUP BY party_id
) pa ON pa.party_id = f.id
WHERE f.company_id = $1
`

type SupplierDuesRow struct {
	ID             int32
	Name           string
	PrimaryPhone   string
	Area           pgtype.Text
	Balance        pgtype.Numeric
	LastPurchaseAt pgtype.Timestamptz
	LastPaymentAt  pgtype.Timestamptz
}

func (q *Queries) SupplierDues(ctx context.Context, companyID int32) ([]SupplierDuesRow, error) {
	rows, err := q.db.Query(ctx, supplierDues, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierDuesRow
	for rows.Next() {
		var i SupplierDuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PrimaryPhone,
			&i.Area,
			&i.Balance,
			&i.LastPurchaseAt,
			&i.LastPaymentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
