// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Factory struct {
	ID            int32
	Name          string
	ContactPerson pgtype.Text
	Phone         pgtype.Text
	Address       pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type Payment struct {
	ID          int32
	PartyType   string
	PartyID     int32
	Amount      pgtype.Numeric
	PaymentMode string
	PaymentDate pgtype.Date
	Notes       pgtype.Text
	CreatedBy   pgtype.Int4
	CreatedAt   pgtype.Timestamptz
}

type Product struct {
	ID            int32
	Name          string
	Unit          string
	PurchasePrice pgtype.Numeric
	SellingPrice  pgtype.Numeric
	CurrentStock  pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
}

type Purchase struct {
	ID           int32
	FactoryID    int32
	InvoiceNo    pgtype.Text
	PurchaseDate pgtype.Date
	TotalAmount  pgtype.Numeric
	AmountPaid   pgtype.Numeric
	CreatedBy    pgtype.Int4
	CreatedAt    pgtype.Timestamptz
}

type PurchaseItem struct {
	ID         int32
	PurchaseID int32
	ProductID  int32
	Quantity   pgtype.Numeric
	UnitPrice  pgtype.Numeric
	LineTotal  pgtype.Numeric
}

type Sale struct {
	ID          int32
	ShopID      int32
	SaleDate    pgtype.Date
	TotalAmount pgtype.Numeric
	AmountPaid  pgtype.Numeric
	PaymentType string
	CreatedBy   pgtype.Int4
	CreatedAt   pgtype.Timestamptz
}

type SaleItem struct {
	ID        int32
	SaleID    int32
	ProductID int32
	Quantity  pgtype.Numeric
	UnitPrice pgtype.Numeric
	LineTotal pgtype.Numeric
}

type Shop struct {
	ID             int32
	Name           string
	OwnerName      pgtype.Text
	Phone          pgtype.Text
	Area           pgtype.Text
	OpeningBalance pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID           int32
	Name         string
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamptz
}
