// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (company_id, party_type, party_id, amount, payment_mode, notes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, party_type, party_id, amount, payment_mode, payment_date, notes, created_by, created_at
`

type CreatePaymentParams struct {
	CompanyID   int32
	PartyType   string
	PartyID     int32
	Amount      pgtype.Numeric
	PaymentMode string
	Notes       pgtype.Text
	CreatedBy   pgtype.Int4
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.CompanyID,
		arg.PartyType,
		arg.PartyID,
		arg.Amount,
		arg.PaymentMode,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PartyType,
		&i.PartyID,
		&i.Amount,
		&i.PaymentMode,
		&i.PaymentDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const factoryBalance = `-- name: FactoryBalance :one
SELECT
  (
    COALESCE((SELECT SUM(pu.total_amount) FROM purchases pu WHERE pu.factory_id = $1 AND pu.company_id = $2 AND pu.status = 'COMPLETED'), 0)
    - COALESCE((SELECT SUM(pu.amount_paid) FROM purchases pu WHERE pu.factory_id = $1 AND pu.company_id = $2 AND pu.status = 'COMPLETED'), 0)
    - COALESCE((SELECT SUM(pay.amount) FROM payments pay WHERE pay.party_type = 'factory' AND pay.party_id = $1 AND pay.company_id = $2), 0)
  )::numeric(12,2) AS balance
`

type FactoryBalanceParams struct {
	FactoryID int32
	CompanyID int32
}

func (q *Queries) FactoryBalance(ctx context.Context, arg FactoryBalanceParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, factoryBalance, arg.FactoryID, arg.CompanyID)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, company_id, party_type, party_id, amount, payment_mode, payment_date, notes, created_by, created_at FROM payments WHERE company_id = $1 ORDER BY payment_date DESC, id DESC
`

func (q *Queries) ListPayments(ctx context.Context, companyID int32) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.PartyType,
			&i.PartyID,
			&i.Amount,
			&i.PaymentMode,
			&i.PaymentDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByParty = `-- name: ListPaymentsByParty :many
SELECT id, company_id, party_type, party_id, amount, payment_mode, payment_date, notes, created_by, created_at FROM payments WHERE company_id = $1 AND party_type = $2 AND party_id = $3 ORDER BY payment_date DESC, id DESC
`

type ListPaymentsByPartyParams struct {
	CompanyID int32
	PartyType string
	PartyID   int32
}

func (q *Queries) ListPaymentsByParty(ctx context.Context, arg ListPaymentsByPartyParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByParty, arg.CompanyID, arg.PartyType, arg.PartyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.PartyType,
			&i.PartyID,
			&i.Amount,
			&i.PaymentMode,
			&i.PaymentDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsFiltered = `-- name: ListPaymentsFiltered :many
SELECT id, company_id, party_type, party_id, amount, payment_mode, payment_date, notes, created_by, created_at FROM payments
WHERE company_id = $1
  AND ($2::date IS NULL OR payment_date >= $2::date)
  AND ($3::date IS NULL OR payment_date <= $3::date)
  AND ($4::text IS NULL OR party_type = $4::text)
ORDER BY payment_date DESC, id DESC
LIMIT $6::int OFFSET $5::int
`

type ListPaymentsFilteredParams struct {
	CompanyID int32
	FromDate  pgtype.Date
	ToDate    pgtype.Date
	PartyType pgtype.Text
	RowOffset int32
	RowLimit  pgtype.Int4
}

// Cycle 5 list filters: ?from=&to= (payment_date), ?party_type=shop|factory, ?limit=&offset=.
func (q *Queries) ListPaymentsFiltered(ctx context.Context, arg ListPaymentsFilteredParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsFiltered,
		arg.CompanyID,
		arg.FromDate,
		arg.ToDate,
		arg.PartyType,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.PartyType,
			&i.PartyID,
			&i.Amount,
			&i.PaymentMode,
			&i.PaymentDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentsFilteredTotals = `-- name: PaymentsFilteredTotals :one
SELECT COUNT(*)::int AS total_count, COALESCE(SUM(amount), 0)::numeric(12,2) AS total_amount
FROM payments
WHERE company_id = $1
  AND ($2::date IS NULL OR payment_date >= $2::date)
  AND ($3::date IS NULL OR payment_date <= $3::date)
  AND ($4::text IS NULL OR party_type = $4::text)
`

type PaymentsFilteredTotalsParams struct {
	CompanyID int32
	FromDate  pgtype.Date
	ToDate    pgtype.Date
	PartyType pgtype.Text
}

type PaymentsFilteredTotalsRow struct {
	TotalCount  int32
	TotalAmount pgtype.Numeric
}

func (q *Queries) PaymentsFilteredTotals(ctx context.Context, arg PaymentsFilteredTotalsParams) (PaymentsFilteredTotalsRow, error) {
	row := q.db.QueryRow(ctx, paymentsFilteredTotals,
		arg.CompanyID,
		arg.FromDate,
		arg.ToDate,
		arg.PartyType,
	)
	var i PaymentsFilteredTotalsRow
	err := row.Scan(&i.TotalCount, &i.TotalAmount)
	return i, err
}

const shopBalance = `-- name: ShopBalance :one
SELECT
  (
    COALESCE((SELECT s.opening_balance FROM shops s WHERE s.id = $1 AND s.company_id = $2), 0)
    + COALESCE((SELECT SUM(sa.total_amount) FROM sales sa WHERE sa.shop_id = $1 AND sa.company_id = $2 AND sa.status = 'COMPLETED'), 0)
    - COALESCE((SELECT SUM(sa.amount_paid) FROM sales sa WHERE sa.shop_id = $1 AND sa.company_id = $2 AND sa.status = 'COMPLETED'), 0)
    - COALESCE((SELECT SUM(pay.amount) FROM payments pay WHERE pay.party_type = 'shop' AND pay.party_id = $1 AND pay.company_id = $2), 0)
  )::numeric(12,2) AS balance
`

type ShopBalanceParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) ShopBalance(ctx context.Context, arg ShopBalanceParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, shopBalance, arg.ID, arg.CompanyID)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}
