// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (party_type, party_id, amount, payment_mode, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, party_type, party_id, amount, payment_mode, payment_date, notes, created_by, created_at
`

type CreatePaymentParams struct {
	PartyType   string
	PartyID     int32
	Amount      pgtype.Numeric
	PaymentMode string
	Notes       pgtype.Text
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.PartyType,
		arg.PartyID,
		arg.Amount,
		arg.PaymentMode,
		arg.Notes,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PartyType,
		&i.PartyID,
		&i.Amount,
		&i.PaymentMode,
		&i.PaymentDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const factoryBalance = `-- name: FactoryBalance :one
SELECT
  (
    COALESCE((SELECT SUM(pu.total_amount) FROM purchases pu WHERE pu.factory_id = $1), 0)
    - COALESCE((SELECT SUM(pu.amount_paid) FROM purchases pu WHERE pu.factory_id = $1), 0)
    - COALESCE((SELECT SUM(pay.amount) FROM payments pay WHERE pay.party_type = 'factory' AND pay.party_id = $1), 0)
  )::numeric(12,2) AS balance
`

func (q *Queries) FactoryBalance(ctx context.Context, factoryID int32) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, factoryBalance, factoryID)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, party_type, party_id, amount, payment_mode, payment_date, notes, created_by, created_at FROM payments ORDER BY payment_date DESC, id DESC
`

func (q *Queries) ListPayments(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.PartyType,
			&i.PartyID,
			&i.Amount,
			&i.PaymentMode,
			&i.PaymentDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByParty = `-- name: ListPaymentsByParty :many
SELECT id, party_type, party_id, amount, payment_mode, payment_date, notes, created_by, created_at FROM payments WHERE party_type = $1 AND party_id = $2 ORDER BY payment_date DESC, id DESC
`

type ListPaymentsByPartyParams struct {
	PartyType string
	PartyID   int32
}

func (q *Queries) ListPaymentsByParty(ctx context.Context, arg ListPaymentsByPartyParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByParty, arg.PartyType, arg.PartyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.PartyType,
			&i.PartyID,
			&i.Amount,
			&i.PaymentMode,
			&i.PaymentDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shopBalance = `-- name: ShopBalance :one
SELECT
  (
    COALESCE((SELECT s.opening_balance FROM shops s WHERE s.id = $1), 0)
    + COALESCE((SELECT SUM(sa.total_amount) FROM sales sa WHERE sa.shop_id = $1), 0)
    - COALESCE((SELECT SUM(sa.amount_paid) FROM sales sa WHERE sa.shop_id = $1), 0)
    - COALESCE((SELECT SUM(pay.amount) FROM payments pay WHERE pay.party_type = 'shop' AND pay.party_id = $1), 0)
  )::numeric(12,2) AS balance
`

func (q *Queries) ShopBalance(ctx context.Context, id int32) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, shopBalance, id)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}
