// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock)
VALUES ($1, $2, $3, $4, $5, $6, $7, 0)
RETURNING id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at
`

type CreateProductParams struct {
	CompanyID           int32
	Name                string
	Sku                 string
	Unit                string
	CategoryID          int32
	SubcategoryID       pgtype.Int4
	CurrentSellingPrice pgtype.Numeric
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CompanyID,
		arg.Name,
		arg.Sku,
		arg.Unit,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.CurrentSellingPrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1 AND company_id = $2
`

type DeleteProductParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.CompanyID)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at FROM products WHERE id = $1 AND company_id = $2
`

type GetProductParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.ID, arg.CompanyID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at FROM products WHERE company_id = $1 ORDER BY name
`

func (q *Queries) ListProducts(ctx context.Context, companyID int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Sku,
			&i.Unit,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.CurrentSellingPrice,
			&i.CurrentStock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $3, sku = $4, unit = $5, category_id = $6, subcategory_id = $7, current_selling_price = $8
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at
`

type UpdateProductParams struct {
	ID                  int32
	CompanyID           int32
	Name                string
	Sku                 string
	Unit                string
	CategoryID          int32
	SubcategoryID       pgtype.Int4
	CurrentSellingPrice pgtype.Numeric
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Sku,
		arg.Unit,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.CurrentSellingPrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
	)
	return i, err
}

const updateProductSellingPrice = `-- name: UpdateProductSellingPrice :one
UPDATE products SET current_selling_price = $3 WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at
`

type UpdateProductSellingPriceParams struct {
	ID                  int32
	CompanyID           int32
	CurrentSellingPrice pgtype.Numeric
}

func (q *Queries) UpdateProductSellingPrice(ctx context.Context, arg UpdateProductSellingPriceParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductSellingPrice, arg.ID, arg.CompanyID, arg.CurrentSellingPrice)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
	)
	return i, err
}
