// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProduct = `-- name: ArchiveProduct :one
UPDATE products SET archived_at = now(), archived_by = $3
WHERE id = $1 AND company_id = $2 AND archived_at IS NULL
RETURNING id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible, pinned, archived_at, archived_by
`

type ArchiveProductParams struct {
	ID         int32
	CompanyID  int32
	ArchivedBy pgtype.Int4
}

// Cycle 5: soft delete; stock on hand is allowed (the app warns about it).
func (q *Queries) ArchiveProduct(ctx context.Context, arg ArchiveProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, archiveProduct, arg.ID, arg.CompanyID, arg.ArchivedBy)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
		&i.Description,
		&i.IsBundle,
		&i.StorefrontVisible,
		&i.Pinned,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock)
VALUES ($1, $2, $3, $4, $5, $6, $7, 0)
RETURNING id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible, pinned, archived_at, archived_by
`

type CreateProductParams struct {
	CompanyID           int32
	Name                string
	Sku                 string
	Unit                string
	CategoryID          int32
	SubcategoryID       pgtype.Int4
	CurrentSellingPrice pgtype.Numeric
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CompanyID,
		arg.Name,
		arg.Sku,
		arg.Unit,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.CurrentSellingPrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
		&i.Description,
		&i.IsBundle,
		&i.StorefrontVisible,
		&i.Pinned,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const getArchivedProductBySku = `-- name: GetArchivedProductBySku :one
SELECT id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible, pinned, archived_at, archived_by FROM products WHERE company_id = $1 AND sku = $2 AND archived_at IS NOT NULL
`

type GetArchivedProductBySkuParams struct {
	CompanyID int32
	Sku       string
}

// An archived product keeps its SKU (UNIQUE (company_id, sku)), so a clash on create/update
// may be with one of these.
func (q *Queries) GetArchivedProductBySku(ctx context.Context, arg GetArchivedProductBySkuParams) (Product, error) {
	row := q.db.QueryRow(ctx, getArchivedProductBySku, arg.CompanyID, arg.Sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
		&i.Description,
		&i.IsBundle,
		&i.StorefrontVisible,
		&i.Pinned,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible, pinned, archived_at, archived_by FROM products WHERE id = $1 AND company_id = $2
`

type GetProductParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.ID, arg.CompanyID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
		&i.Description,
		&i.IsBundle,
		&i.StorefrontVisible,
		&i.Pinned,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const getStorefrontProduct = `-- name: GetStorefrontProduct :one
SELECT id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible, pinned, archived_at, archived_by FROM products WHERE id = $1 AND company_id = $2 AND storefront_visible = true AND archived_at IS NULL
`

type GetStorefrontProductParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) GetStorefrontProduct(ctx context.Context, arg GetStorefrontProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getStorefrontProduct, arg.ID, arg.CompanyID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
		&i.Description,
		&i.IsBundle,
		&i.StorefrontVisible,
		&i.Pinned,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible, pinned, archived_at, archived_by FROM products WHERE company_id = $1 AND archived_at IS NULL ORDER BY name
`

// Active (non-archived) only: what lists, pickers and new bills may use (Cycle 5).
func (q *Queries) ListProducts(ctx context.Context, companyID int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Sku,
			&i.Unit,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.CurrentSellingPrice,
			&i.CurrentStock,
			&i.CreatedAt,
			&i.Description,
			&i.IsBundle,
			&i.StorefrontVisible,
			&i.Pinned,
			&i.ArchivedAt,
			&i.ArchivedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsIncludingArchived = `-- name: ListProductsIncludingArchived :many
SELECT id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible, pinned, archived_at, archived_by FROM products WHERE company_id = $1 ORDER BY archived_at IS NOT NULL, name
`

func (q *Queries) ListProductsIncludingArchived(ctx context.Context, companyID int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsIncludingArchived, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Sku,
			&i.Unit,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.CurrentSellingPrice,
			&i.CurrentStock,
			&i.CreatedAt,
			&i.Description,
			&i.IsBundle,
			&i.StorefrontVisible,
			&i.Pinned,
			&i.ArchivedAt,
			&i.ArchivedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorefrontProducts = `-- name: ListStorefrontProducts :many
SELECT id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible, pinned, archived_at, archived_by FROM products WHERE company_id = $1 AND storefront_visible = true AND archived_at IS NULL ORDER BY name
`

func (q *Queries) ListStorefrontProducts(ctx context.Context, companyID int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, listStorefrontProducts, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Sku,
			&i.Unit,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.CurrentSellingPrice,
			&i.CurrentStock,
			&i.CreatedAt,
			&i.Description,
			&i.IsBundle,
			&i.StorefrontVisible,
			&i.Pinned,
			&i.ArchivedAt,
			&i.ArchivedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProduct = `-- name: RestoreProduct :one
UPDATE products SET archived_at = NULL, archived_by = NULL
WHERE id = $1 AND company_id = $2 AND archived_at IS NOT NULL
RETURNING id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible, pinned, archived_at, archived_by
`

type RestoreProductParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) RestoreProduct(ctx context.Context, arg RestoreProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, restoreProduct, arg.ID, arg.CompanyID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
		&i.Description,
		&i.IsBundle,
		&i.StorefrontVisible,
		&i.Pinned,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $3, sku = $4, unit = $5, category_id = $6, subcategory_id = $7, current_selling_price = $8
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible, pinned, archived_at, archived_by
`

type UpdateProductParams struct {
	ID                  int32
	CompanyID           int32
	Name                string
	Sku                 string
	Unit                string
	CategoryID          int32
	SubcategoryID       pgtype.Int4
	CurrentSellingPrice pgtype.Numeric
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Sku,
		arg.Unit,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.CurrentSellingPrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
		&i.Description,
		&i.IsBundle,
		&i.StorefrontVisible,
		&i.Pinned,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const updateProductSellingPrice = `-- name: UpdateProductSellingPrice :one
UPDATE products SET current_selling_price = $3 WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible, pinned, archived_at, archived_by
`

type UpdateProductSellingPriceParams struct {
	ID                  int32
	CompanyID           int32
	CurrentSellingPrice pgtype.Numeric
}

func (q *Queries) UpdateProductSellingPrice(ctx context.Context, arg UpdateProductSellingPriceParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductSellingPrice, arg.ID, arg.CompanyID, arg.CurrentSellingPrice)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
		&i.Description,
		&i.IsBundle,
		&i.StorefrontVisible,
		&i.Pinned,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}

const updateProductStorefront = `-- name: UpdateProductStorefront :one
UPDATE products
SET description = $3, is_bundle = $4, storefront_visible = $5
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible, pinned, archived_at, archived_by
`

type UpdateProductStorefrontParams struct {
	ID                int32
	CompanyID         int32
	Description       pgtype.Text
	IsBundle          bool
	StorefrontVisible bool
}

func (q *Queries) UpdateProductStorefront(ctx context.Context, arg UpdateProductStorefrontParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStorefront,
		arg.ID,
		arg.CompanyID,
		arg.Description,
		arg.IsBundle,
		arg.StorefrontVisible,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
		&i.Description,
		&i.IsBundle,
		&i.StorefrontVisible,
		&i.Pinned,
		&i.ArchivedAt,
		&i.ArchivedBy,
	)
	return i, err
}
