// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_images.sql

package db

import (
	"context"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (company_id, product_id, url, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, company_id, product_id, url, sort_order, created_at
`

type CreateProductImageParams struct {
	CompanyID int32
	ProductID int32
	Url       string
	SortOrder int32
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage,
		arg.CompanyID,
		arg.ProductID,
		arg.Url,
		arg.SortOrder,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ProductID,
		&i.Url,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images WHERE id = $1 AND company_id = $2
`

type DeleteProductImageParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) DeleteProductImage(ctx context.Context, arg DeleteProductImageParams) error {
	_, err := q.db.Exec(ctx, deleteProductImage, arg.ID, arg.CompanyID)
	return err
}

const getProductImage = `-- name: GetProductImage :one
SELECT id, company_id, product_id, url, sort_order, created_at FROM product_images WHERE id = $1 AND company_id = $2
`

type GetProductImageParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) GetProductImage(ctx context.Context, arg GetProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, getProductImage, arg.ID, arg.CompanyID)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ProductID,
		&i.Url,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, company_id, product_id, url, sort_order, created_at FROM product_images WHERE product_id = $1 AND company_id = $2 ORDER BY sort_order, id
`

type ListProductImagesParams struct {
	ProductID int32
	CompanyID int32
}

func (q *Queries) ListProductImages(ctx context.Context, arg ListProductImagesParams) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImages, arg.ProductID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ProductID,
			&i.Url,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
