// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_pack_items.sql

package db

import (
	"context"
)

const createProductPackItem = `-- name: CreateProductPackItem :one
INSERT INTO product_pack_items (company_id, product_id, size, quantity)
VALUES ($1, $2, $3, $4)
RETURNING id, company_id, product_id, size, quantity
`

type CreateProductPackItemParams struct {
	CompanyID int32
	ProductID int32
	Size      string
	Quantity  int32
}

func (q *Queries) CreateProductPackItem(ctx context.Context, arg CreateProductPackItemParams) (ProductPackItem, error) {
	row := q.db.QueryRow(ctx, createProductPackItem,
		arg.CompanyID,
		arg.ProductID,
		arg.Size,
		arg.Quantity,
	)
	var i ProductPackItem
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ProductID,
		&i.Size,
		&i.Quantity,
	)
	return i, err
}

const deleteProductPackItems = `-- name: DeleteProductPackItems :exec
DELETE FROM product_pack_items WHERE product_id = $1 AND company_id = $2
`

type DeleteProductPackItemsParams struct {
	ProductID int32
	CompanyID int32
}

func (q *Queries) DeleteProductPackItems(ctx context.Context, arg DeleteProductPackItemsParams) error {
	_, err := q.db.Exec(ctx, deleteProductPackItems, arg.ProductID, arg.CompanyID)
	return err
}

const listProductPackItems = `-- name: ListProductPackItems :many
SELECT id, company_id, product_id, size, quantity FROM product_pack_items WHERE product_id = $1 AND company_id = $2
ORDER BY CASE size
    WHEN 'S' THEN 1 WHEN 'M' THEN 2 WHEN 'L' THEN 3 WHEN 'XL' THEN 4
    WHEN 'XXL' THEN 5 WHEN 'XXXL' THEN 6 ELSE 7
END
`

type ListProductPackItemsParams struct {
	ProductID int32
	CompanyID int32
}

func (q *Queries) ListProductPackItems(ctx context.Context, arg ListProductPackItemsParams) ([]ProductPackItem, error) {
	rows, err := q.db.Query(ctx, listProductPackItems, arg.ProductID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductPackItem
	for rows.Next() {
		var i ProductPackItem
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ProductID,
			&i.Size,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
