// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPublicOrder = `-- name: CreatePublicOrder :one
INSERT INTO public_orders (company_id, customer_name, customer_phone, customer_address, fulfillment_method, total_amount)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, customer_name, customer_phone, customer_address, fulfillment_method, status, total_amount, created_at
`

type CreatePublicOrderParams struct {
	CompanyID         int32
	CustomerName      string
	CustomerPhone     string
	CustomerAddress   pgtype.Text
	FulfillmentMethod string
	TotalAmount       pgtype.Numeric
}

func (q *Queries) CreatePublicOrder(ctx context.Context, arg CreatePublicOrderParams) (PublicOrder, error) {
	row := q.db.QueryRow(ctx, createPublicOrder,
		arg.CompanyID,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.CustomerAddress,
		arg.FulfillmentMethod,
		arg.TotalAmount,
	)
	var i PublicOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.FulfillmentMethod,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const createPublicOrderItem = `-- name: CreatePublicOrderItem :one
INSERT INTO public_order_items (order_id, product_id, quantity, unit_price, line_total)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, product_id, quantity, unit_price, line_total
`

type CreatePublicOrderItemParams struct {
	OrderID   int32
	ProductID int32
	Quantity  int32
	UnitPrice pgtype.Numeric
	LineTotal pgtype.Numeric
}

func (q *Queries) CreatePublicOrderItem(ctx context.Context, arg CreatePublicOrderItemParams) (PublicOrderItem, error) {
	row := q.db.QueryRow(ctx, createPublicOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
	)
	var i PublicOrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
	)
	return i, err
}

const getPublicOrder = `-- name: GetPublicOrder :one
SELECT id, company_id, customer_name, customer_phone, customer_address, fulfillment_method, status, total_amount, created_at FROM public_orders WHERE id = $1 AND company_id = $2
`

type GetPublicOrderParams struct {
	ID        int32
	CompanyID int32
}

func (q *Queries) GetPublicOrder(ctx context.Context, arg GetPublicOrderParams) (PublicOrder, error) {
	row := q.db.QueryRow(ctx, getPublicOrder, arg.ID, arg.CompanyID)
	var i PublicOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.FulfillmentMethod,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const listPublicOrderItems = `-- name: ListPublicOrderItems :many
SELECT poi.id, poi.order_id, poi.product_id, p.name AS product_name, poi.quantity, poi.unit_price, poi.line_total
FROM public_order_items poi
JOIN products p ON p.id = poi.product_id
WHERE poi.order_id = $1
`

type ListPublicOrderItemsRow struct {
	ID          int32
	OrderID     int32
	ProductID   int32
	ProductName string
	Quantity    int32
	UnitPrice   pgtype.Numeric
	LineTotal   pgtype.Numeric
}

func (q *Queries) ListPublicOrderItems(ctx context.Context, orderID int32) ([]ListPublicOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, listPublicOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicOrderItemsRow
	for rows.Next() {
		var i ListPublicOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicOrders = `-- name: ListPublicOrders :many
SELECT id, company_id, customer_name, customer_phone, customer_address, fulfillment_method, status, total_amount, created_at FROM public_orders WHERE company_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPublicOrders(ctx context.Context, companyID int32) ([]PublicOrder, error) {
	rows, err := q.db.Query(ctx, listPublicOrders, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicOrder
	for rows.Next() {
		var i PublicOrder
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CustomerAddress,
			&i.FulfillmentMethod,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePublicOrderStatus = `-- name: UpdatePublicOrderStatus :one
UPDATE public_orders SET status = $3 WHERE id = $1 AND company_id = $2
RETURNING id, company_id, customer_name, customer_phone, customer_address, fulfillment_method, status, total_amount, created_at
`

type UpdatePublicOrderStatusParams struct {
	ID        int32
	CompanyID int32
	Status    string
}

func (q *Queries) UpdatePublicOrderStatus(ctx context.Context, arg UpdatePublicOrderStatusParams) (PublicOrder, error) {
	row := q.db.QueryRow(ctx, updatePublicOrderStatus, arg.ID, arg.CompanyID, arg.Status)
	var i PublicOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.FulfillmentMethod,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}
