// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchases (factory_id, invoice_no, total_amount, amount_paid, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, factory_id, invoice_no, purchase_date, total_amount, amount_paid, created_by, created_at
`

type CreatePurchaseParams struct {
	FactoryID   int32
	InvoiceNo   pgtype.Text
	TotalAmount pgtype.Numeric
	AmountPaid  pgtype.Numeric
	CreatedBy   pgtype.Int4
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, createPurchase,
		arg.FactoryID,
		arg.InvoiceNo,
		arg.TotalAmount,
		arg.AmountPaid,
		arg.CreatedBy,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.FactoryID,
		&i.InvoiceNo,
		&i.PurchaseDate,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createPurchaseItem = `-- name: CreatePurchaseItem :one
INSERT INTO purchase_items (purchase_id, product_id, quantity, unit_price, line_total)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, purchase_id, product_id, quantity, unit_price, line_total
`

type CreatePurchaseItemParams struct {
	PurchaseID int32
	ProductID  int32
	Quantity   pgtype.Numeric
	UnitPrice  pgtype.Numeric
	LineTotal  pgtype.Numeric
}

func (q *Queries) CreatePurchaseItem(ctx context.Context, arg CreatePurchaseItemParams) (PurchaseItem, error) {
	row := q.db.QueryRow(ctx, createPurchaseItem,
		arg.PurchaseID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
	)
	var i PurchaseItem
	err := row.Scan(
		&i.ID,
		&i.PurchaseID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
	)
	return i, err
}

const incrementProductStock = `-- name: IncrementProductStock :exec
UPDATE products SET current_stock = current_stock + $2 WHERE id = $1
`

type IncrementProductStockParams struct {
	ID           int32
	CurrentStock pgtype.Numeric
}

func (q *Queries) IncrementProductStock(ctx context.Context, arg IncrementProductStockParams) error {
	_, err := q.db.Exec(ctx, incrementProductStock, arg.ID, arg.CurrentStock)
	return err
}

const listPurchaseItems = `-- name: ListPurchaseItems :many
SELECT pi.id, pi.purchase_id, pi.product_id, pr.name AS product_name,
       pi.quantity, pi.unit_price, pi.line_total
FROM purchase_items pi
JOIN products pr ON pr.id = pi.product_id
WHERE pi.purchase_id = $1
`

type ListPurchaseItemsRow struct {
	ID          int32
	PurchaseID  int32
	ProductID   int32
	ProductName string
	Quantity    pgtype.Numeric
	UnitPrice   pgtype.Numeric
	LineTotal   pgtype.Numeric
}

func (q *Queries) ListPurchaseItems(ctx context.Context, purchaseID int32) ([]ListPurchaseItemsRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseItems, purchaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchaseItemsRow
	for rows.Next() {
		var i ListPurchaseItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PurchaseID,
			&i.ProductID,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchases = `-- name: ListPurchases :many
SELECT p.id, p.factory_id, f.name AS factory_name, p.invoice_no, p.purchase_date,
       p.total_amount, p.amount_paid, p.created_at
FROM purchases p
JOIN factories f ON f.id = p.factory_id
ORDER BY p.purchase_date DESC, p.id DESC
`

type ListPurchasesRow struct {
	ID           int32
	FactoryID    int32
	FactoryName  string
	InvoiceNo    pgtype.Text
	PurchaseDate pgtype.Date
	TotalAmount  pgtype.Numeric
	AmountPaid   pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListPurchases(ctx context.Context) ([]ListPurchasesRow, error) {
	rows, err := q.db.Query(ctx, listPurchases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchasesRow
	for rows.Next() {
		var i ListPurchasesRow
		if err := rows.Scan(
			&i.ID,
			&i.FactoryID,
			&i.FactoryName,
			&i.InvoiceNo,
			&i.PurchaseDate,
			&i.TotalAmount,
			&i.AmountPaid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
