// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const factoryPayables = `-- name: FactoryPayables :many
SELECT
  f.id,
  f.name,
  (
    COALESCE(pu_agg.total, 0)
    - COALESCE(pu_agg.paid, 0)
    - COALESCE(pay_agg.paid, 0)
  )::numeric(12,2) AS balance
FROM factories f
LEFT JOIN (
  SELECT factory_id, SUM(total_amount) AS total, SUM(amount_paid) AS paid
  FROM purchases GROUP BY factory_id
) pu_agg ON pu_agg.factory_id = f.id
LEFT JOIN (
  SELECT party_id, SUM(amount) AS paid
  FROM payments WHERE party_type = 'factory' GROUP BY party_id
) pay_agg ON pay_agg.party_id = f.id
ORDER BY balance DESC
`

type FactoryPayablesRow struct {
	ID      int32
	Name    string
	Balance pgtype.Numeric
}

func (q *Queries) FactoryPayables(ctx context.Context) ([]FactoryPayablesRow, error) {
	rows, err := q.db.Query(ctx, factoryPayables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FactoryPayablesRow
	for rows.Next() {
		var i FactoryPayablesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lowStockProducts = `-- name: LowStockProducts :many
SELECT id, name, unit, purchase_price, selling_price, current_stock, created_at FROM products WHERE current_stock < 10 ORDER BY current_stock ASC
`

func (q *Queries) LowStockProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, lowStockProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.PurchasePrice,
			&i.SellingPrice,
			&i.CurrentStock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profitSummary = `-- name: ProfitSummary :one
SELECT
  COALESCE(SUM((si.unit_price - p.purchase_price) * si.quantity), 0)::numeric(12,2) AS profit
FROM sale_items si
JOIN products p ON p.id = si.product_id
`

func (q *Queries) ProfitSummary(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, profitSummary)
	var profit pgtype.Numeric
	err := row.Scan(&profit)
	return profit, err
}

const shopDues = `-- name: ShopDues :many
SELECT
  s.id,
  s.name,
  (
    COALESCE(s.opening_balance, 0)
    + COALESCE(sales_agg.total, 0)
    - COALESCE(sales_agg.paid, 0)
    - COALESCE(pay_agg.paid, 0)
  )::numeric(12,2) AS balance
FROM shops s
LEFT JOIN (
  SELECT shop_id, SUM(total_amount) AS total, SUM(amount_paid) AS paid
  FROM sales GROUP BY shop_id
) sales_agg ON sales_agg.shop_id = s.id
LEFT JOIN (
  SELECT party_id, SUM(amount) AS paid
  FROM payments WHERE party_type = 'shop' GROUP BY party_id
) pay_agg ON pay_agg.party_id = s.id
ORDER BY balance DESC
`

type ShopDuesRow struct {
	ID      int32
	Name    string
	Balance pgtype.Numeric
}

func (q *Queries) ShopDues(ctx context.Context) ([]ShopDuesRow, error) {
	rows, err := q.db.Query(ctx, shopDues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopDuesRow
	for rows.Next() {
		var i ShopDuesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayPurchasesSummary = `-- name: TodayPurchasesSummary :one
SELECT
  COUNT(*)::int AS count,
  COALESCE(SUM(total_amount), 0)::numeric(12,2) AS total
FROM purchases
WHERE purchase_date = CURRENT_DATE
`

type TodayPurchasesSummaryRow struct {
	Count int32
	Total pgtype.Numeric
}

func (q *Queries) TodayPurchasesSummary(ctx context.Context) (TodayPurchasesSummaryRow, error) {
	row := q.db.QueryRow(ctx, todayPurchasesSummary)
	var i TodayPurchasesSummaryRow
	err := row.Scan(&i.Count, &i.Total)
	return i, err
}

const todaySalesSummary = `-- name: TodaySalesSummary :one
SELECT
  COUNT(*)::int AS count,
  COALESCE(SUM(total_amount), 0)::numeric(12,2) AS total
FROM sales
WHERE sale_date = CURRENT_DATE
`

type TodaySalesSummaryRow struct {
	Count int32
	Total pgtype.Numeric
}

func (q *Queries) TodaySalesSummary(ctx context.Context) (TodaySalesSummaryRow, error) {
	row := q.db.QueryRow(ctx, todaySalesSummary)
	var i TodaySalesSummaryRow
	err := row.Scan(&i.Count, &i.Total)
	return i, err
}
