// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const factoryPayables = `-- name: FactoryPayables :many
SELECT
  f.id,
  f.name,
  (
    COALESCE(pu_agg.total, 0)
    - COALESCE(pu_agg.paid, 0)
    - COALESCE(pay_agg.paid, 0)
  )::numeric(12,2) AS balance
FROM factories f
LEFT JOIN (
  SELECT factory_id, SUM(total_amount) AS total, SUM(amount_paid) AS paid
  FROM purchases WHERE purchases.company_id = $1 AND status = 'COMPLETED' GROUP BY factory_id
) pu_agg ON pu_agg.factory_id = f.id
LEFT JOIN (
  SELECT party_id, SUM(amount) AS paid
  FROM payments WHERE payments.company_id = $1 AND party_type = 'factory' GROUP BY party_id
) pay_agg ON pay_agg.party_id = f.id
WHERE f.company_id = $1
ORDER BY balance DESC
`

type FactoryPayablesRow struct {
	ID      int32
	Name    string
	Balance pgtype.Numeric
}

func (q *Queries) FactoryPayables(ctx context.Context, companyID int32) ([]FactoryPayablesRow, error) {
	rows, err := q.db.Query(ctx, factoryPayables, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FactoryPayablesRow
	for rows.Next() {
		var i FactoryPayablesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lowStockProducts = `-- name: LowStockProducts :many
SELECT id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at FROM products WHERE company_id = $1 AND current_stock < 10 ORDER BY current_stock ASC
`

func (q *Queries) LowStockProducts(ctx context.Context, companyID int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, lowStockProducts, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Sku,
			&i.Unit,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.CurrentSellingPrice,
			&i.CurrentStock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profitSummary = `-- name: ProfitSummary :one
SELECT
  COALESCE(SUM(si.line_total), 0)::numeric(12,2) -
  COALESCE((
    SELECT SUM(sicc.quantity * sicc.unit_cost)
    FROM sale_item_cost_consumptions sicc
    JOIN sale_items sii ON sii.id = sicc.sale_item_id
    JOIN sales ss ON ss.id = sii.sale_id
    WHERE ss.company_id = $1 AND ss.status = 'COMPLETED'
  ), 0)::numeric(12,2) AS profit
FROM sale_items si
JOIN sales s ON s.id = si.sale_id
WHERE s.company_id = $1 AND s.status = 'COMPLETED'
`

func (q *Queries) ProfitSummary(ctx context.Context, companyID int32) (int32, error) {
	row := q.db.QueryRow(ctx, profitSummary, companyID)
	var profit int32
	err := row.Scan(&profit)
	return profit, err
}

const shopDues = `-- name: ShopDues :many
SELECT
  s.id,
  s.name,
  (
    COALESCE(s.opening_balance, 0)
    + COALESCE(sales_agg.total, 0)
    - COALESCE(sales_agg.paid, 0)
    - COALESCE(pay_agg.paid, 0)
  )::numeric(12,2) AS balance
FROM shops s
LEFT JOIN (
  SELECT shop_id, SUM(total_amount) AS total, SUM(amount_paid) AS paid
  FROM sales WHERE sales.company_id = $1 AND status = 'COMPLETED' GROUP BY shop_id
) sales_agg ON sales_agg.shop_id = s.id
LEFT JOIN (
  SELECT party_id, SUM(amount) AS paid
  FROM payments WHERE payments.company_id = $1 AND party_type = 'shop' GROUP BY party_id
) pay_agg ON pay_agg.party_id = s.id
WHERE s.company_id = $1
ORDER BY balance DESC
`

type ShopDuesRow struct {
	ID      int32
	Name    string
	Balance pgtype.Numeric
}

func (q *Queries) ShopDues(ctx context.Context, companyID int32) ([]ShopDuesRow, error) {
	rows, err := q.db.Query(ctx, shopDues, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopDuesRow
	for rows.Next() {
		var i ShopDuesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayPurchasesSummary = `-- name: TodayPurchasesSummary :one
SELECT
  COUNT(*)::int AS count,
  COALESCE(SUM(total_amount), 0)::numeric(12,2) AS total
FROM purchases
WHERE company_id = $1 AND purchase_date = CURRENT_DATE AND status = 'COMPLETED'
`

type TodayPurchasesSummaryRow struct {
	Count int32
	Total pgtype.Numeric
}

func (q *Queries) TodayPurchasesSummary(ctx context.Context, companyID int32) (TodayPurchasesSummaryRow, error) {
	row := q.db.QueryRow(ctx, todayPurchasesSummary, companyID)
	var i TodayPurchasesSummaryRow
	err := row.Scan(&i.Count, &i.Total)
	return i, err
}

const todaySalesSummary = `-- name: TodaySalesSummary :one
SELECT
  COUNT(*)::int AS count,
  COALESCE(SUM(total_amount), 0)::numeric(12,2) AS total
FROM sales
WHERE company_id = $1 AND sale_date = CURRENT_DATE AND status = 'COMPLETED'
`

type TodaySalesSummaryRow struct {
	Count int32
	Total pgtype.Numeric
}

func (q *Queries) TodaySalesSummary(ctx context.Context, companyID int32) (TodaySalesSummaryRow, error) {
	row := q.db.QueryRow(ctx, todaySalesSummary, companyID)
	var i TodaySalesSummaryRow
	err := row.Scan(&i.Count, &i.Total)
	return i, err
}
