// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSale = `-- name: CancelSale :one
UPDATE sales
SET status = 'CANCELLED', cancelled_reason = $3, cancelled_by = $4, cancelled_at = now()
WHERE id = $1 AND company_id = $2 AND status = 'COMPLETED'
RETURNING id, company_id, bill_number, shop_id, sale_date, total_amount, amount_paid, payment_type, status, cancelled_reason, cancelled_by, cancelled_at, created_by, created_at
`

type CancelSaleParams struct {
	ID              int32
	CompanyID       int32
	CancelledReason pgtype.Text
	CancelledBy     pgtype.Int4
}

func (q *Queries) CancelSale(ctx context.Context, arg CancelSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, cancelSale,
		arg.ID,
		arg.CompanyID,
		arg.CancelledReason,
		arg.CancelledBy,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BillNumber,
		&i.ShopID,
		&i.SaleDate,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.PaymentType,
		&i.Status,
		&i.CancelledReason,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSale = `-- name: CreateSale :one
INSERT INTO sales (company_id, bill_number, shop_id, total_amount, amount_paid, payment_type, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, bill_number, shop_id, sale_date, total_amount, amount_paid, payment_type, status, cancelled_reason, cancelled_by, cancelled_at, created_by, created_at
`

type CreateSaleParams struct {
	CompanyID   int32
	BillNumber  string
	ShopID      int32
	TotalAmount pgtype.Numeric
	AmountPaid  pgtype.Numeric
	PaymentType string
	CreatedBy   pgtype.Int4
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.CompanyID,
		arg.BillNumber,
		arg.ShopID,
		arg.TotalAmount,
		arg.AmountPaid,
		arg.PaymentType,
		arg.CreatedBy,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BillNumber,
		&i.ShopID,
		&i.SaleDate,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.PaymentType,
		&i.Status,
		&i.CancelledReason,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSaleItem = `-- name: CreateSaleItem :one
INSERT INTO sale_items (sale_id, product_id, unit, quantity, unit_price, line_total, below_cost)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, sale_id, product_id, unit, quantity, unit_price, line_total, below_cost
`

type CreateSaleItemParams struct {
	SaleID    int32
	ProductID int32
	Unit      string
	Quantity  pgtype.Numeric
	UnitPrice pgtype.Numeric
	LineTotal pgtype.Numeric
	BelowCost bool
}

func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, createSaleItem,
		arg.SaleID,
		arg.ProductID,
		arg.Unit,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
		arg.BelowCost,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.Unit,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
		&i.BelowCost,
	)
	return i, err
}

const decrementProductStock = `-- name: DecrementProductStock :one
UPDATE products
SET current_stock = current_stock - $2
WHERE id = $1 AND current_stock >= $2
RETURNING id, company_id, name, sku, unit, category_id, subcategory_id, current_selling_price, current_stock, created_at, description, is_bundle, storefront_visible
`

type DecrementProductStockParams struct {
	ID           int32
	CurrentStock pgtype.Numeric
}

func (q *Queries) DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, decrementProductStock, arg.ID, arg.CurrentStock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Sku,
		&i.Unit,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.CurrentSellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
		&i.Description,
		&i.IsBundle,
		&i.StorefrontVisible,
	)
	return i, err
}

const getSaleByID = `-- name: GetSaleByID :one
SELECT s.id, s.company_id, s.bill_number, s.shop_id, sh.name AS shop_name, sh.primary_phone AS shop_phone,
       s.sale_date, s.total_amount, s.amount_paid, s.payment_type, s.status,
       s.cancelled_reason, s.cancelled_by, s.cancelled_at, s.created_by, s.created_at
FROM sales s
JOIN shops sh ON sh.id = s.shop_id
WHERE s.id = $1 AND s.company_id = $2
`

type GetSaleByIDParams struct {
	ID        int32
	CompanyID int32
}

type GetSaleByIDRow struct {
	ID              int32
	CompanyID       int32
	BillNumber      string
	ShopID          int32
	ShopName        string
	ShopPhone       string
	SaleDate        pgtype.Date
	TotalAmount     pgtype.Numeric
	AmountPaid      pgtype.Numeric
	PaymentType     string
	Status          string
	CancelledReason pgtype.Text
	CancelledBy     pgtype.Int4
	CancelledAt     pgtype.Timestamptz
	CreatedBy       pgtype.Int4
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetSaleByID(ctx context.Context, arg GetSaleByIDParams) (GetSaleByIDRow, error) {
	row := q.db.QueryRow(ctx, getSaleByID, arg.ID, arg.CompanyID)
	var i GetSaleByIDRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BillNumber,
		&i.ShopID,
		&i.ShopName,
		&i.ShopPhone,
		&i.SaleDate,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.PaymentType,
		&i.Status,
		&i.CancelledReason,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const incrementProductStockUnchecked = `-- name: IncrementProductStockUnchecked :exec
UPDATE products SET current_stock = current_stock + $2 WHERE id = $1
`

type IncrementProductStockUncheckedParams struct {
	ID           int32
	CurrentStock pgtype.Numeric
}

func (q *Queries) IncrementProductStockUnchecked(ctx context.Context, arg IncrementProductStockUncheckedParams) error {
	_, err := q.db.Exec(ctx, incrementProductStockUnchecked, arg.ID, arg.CurrentStock)
	return err
}

const listSaleItems = `-- name: ListSaleItems :many
SELECT si.id, si.sale_id, si.product_id, pr.name AS product_name, pr.sku AS product_sku,
       si.unit, si.quantity, si.unit_price, si.line_total, si.below_cost
FROM sale_items si
JOIN products pr ON pr.id = si.product_id
WHERE si.sale_id = $1
`

type ListSaleItemsRow struct {
	ID          int32
	SaleID      int32
	ProductID   int32
	ProductName string
	ProductSku  string
	Unit        string
	Quantity    pgtype.Numeric
	UnitPrice   pgtype.Numeric
	LineTotal   pgtype.Numeric
	BelowCost   bool
}

func (q *Queries) ListSaleItems(ctx context.Context, saleID int32) ([]ListSaleItemsRow, error) {
	rows, err := q.db.Query(ctx, listSaleItems, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSaleItemsRow
	for rows.Next() {
		var i ListSaleItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.ProductID,
			&i.ProductName,
			&i.ProductSku,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
			&i.BelowCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSales = `-- name: ListSales :many
SELECT s.id, s.company_id, s.bill_number, s.shop_id, sh.name AS shop_name, s.sale_date, s.total_amount,
       s.amount_paid, s.payment_type, s.status, s.created_at
FROM sales s
JOIN shops sh ON sh.id = s.shop_id
WHERE s.company_id = $1
ORDER BY s.sale_date DESC, s.id DESC
`

type ListSalesRow struct {
	ID          int32
	CompanyID   int32
	BillNumber  string
	ShopID      int32
	ShopName    string
	SaleDate    pgtype.Date
	TotalAmount pgtype.Numeric
	AmountPaid  pgtype.Numeric
	PaymentType string
	Status      string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListSales(ctx context.Context, companyID int32) ([]ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesRow
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BillNumber,
			&i.ShopID,
			&i.ShopName,
			&i.SaleDate,
			&i.TotalAmount,
			&i.AmountPaid,
			&i.PaymentType,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
