// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSale = `-- name: CreateSale :one
INSERT INTO sales (shop_id, total_amount, amount_paid, payment_type)
VALUES ($1, $2, $3, $4)
RETURNING id, shop_id, sale_date, total_amount, amount_paid, payment_type, created_by, created_at
`

type CreateSaleParams struct {
	ShopID      int32
	TotalAmount pgtype.Numeric
	AmountPaid  pgtype.Numeric
	PaymentType string
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.ShopID,
		arg.TotalAmount,
		arg.AmountPaid,
		arg.PaymentType,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.SaleDate,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.PaymentType,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSaleItem = `-- name: CreateSaleItem :one
INSERT INTO sale_items (sale_id, product_id, quantity, unit_price, line_total)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, sale_id, product_id, quantity, unit_price, line_total
`

type CreateSaleItemParams struct {
	SaleID    int32
	ProductID int32
	Quantity  pgtype.Numeric
	UnitPrice pgtype.Numeric
	LineTotal pgtype.Numeric
}

func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, createSaleItem,
		arg.SaleID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
	)
	return i, err
}

const decrementProductStock = `-- name: DecrementProductStock :one
UPDATE products
SET current_stock = current_stock - $2
WHERE id = $1 AND current_stock >= $2
RETURNING id, name, unit, purchase_price, selling_price, current_stock, created_at
`

type DecrementProductStockParams struct {
	ID           int32
	CurrentStock pgtype.Numeric
}

func (q *Queries) DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, decrementProductStock, arg.ID, arg.CurrentStock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.PurchasePrice,
		&i.SellingPrice,
		&i.CurrentStock,
		&i.CreatedAt,
	)
	return i, err
}

const listSaleItems = `-- name: ListSaleItems :many
SELECT si.id, si.sale_id, si.product_id, pr.name AS product_name,
       si.quantity, si.unit_price, si.line_total
FROM sale_items si
JOIN products pr ON pr.id = si.product_id
WHERE si.sale_id = $1
`

type ListSaleItemsRow struct {
	ID          int32
	SaleID      int32
	ProductID   int32
	ProductName string
	Quantity    pgtype.Numeric
	UnitPrice   pgtype.Numeric
	LineTotal   pgtype.Numeric
}

func (q *Queries) ListSaleItems(ctx context.Context, saleID int32) ([]ListSaleItemsRow, error) {
	rows, err := q.db.Query(ctx, listSaleItems, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSaleItemsRow
	for rows.Next() {
		var i ListSaleItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.ProductID,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSales = `-- name: ListSales :many
SELECT s.id, s.shop_id, sh.name AS shop_name, s.sale_date, s.total_amount, s.amount_paid, s.payment_type, s.created_at
FROM sales s
JOIN shops sh ON sh.id = s.shop_id
ORDER BY s.sale_date DESC, s.id DESC
`

type ListSalesRow struct {
	ID          int32
	ShopID      int32
	ShopName    string
	SaleDate    pgtype.Date
	TotalAmount pgtype.Numeric
	AmountPaid  pgtype.Numeric
	PaymentType string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListSales(ctx context.Context) ([]ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesRow
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ShopName,
			&i.SaleDate,
			&i.TotalAmount,
			&i.AmountPaid,
			&i.PaymentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
