// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shops.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShop = `-- name: CreateShop :one
INSERT INTO shops (name, owner_name, phone, area, opening_balance)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, owner_name, phone, area, opening_balance, created_at
`

type CreateShopParams struct {
	Name           string
	OwnerName      pgtype.Text
	Phone          pgtype.Text
	Area           pgtype.Text
	OpeningBalance pgtype.Numeric
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, createShop,
		arg.Name,
		arg.OwnerName,
		arg.Phone,
		arg.Area,
		arg.OpeningBalance,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerName,
		&i.Phone,
		&i.Area,
		&i.OpeningBalance,
		&i.CreatedAt,
	)
	return i, err
}

const deleteShop = `-- name: DeleteShop :exec
DELETE FROM shops WHERE id = $1
`

func (q *Queries) DeleteShop(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteShop, id)
	return err
}

const getShop = `-- name: GetShop :one
SELECT id, name, owner_name, phone, area, opening_balance, created_at FROM shops WHERE id = $1
`

func (q *Queries) GetShop(ctx context.Context, id int32) (Shop, error) {
	row := q.db.QueryRow(ctx, getShop, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerName,
		&i.Phone,
		&i.Area,
		&i.OpeningBalance,
		&i.CreatedAt,
	)
	return i, err
}

const listShops = `-- name: ListShops :many
SELECT id, name, owner_name, phone, area, opening_balance, created_at FROM shops ORDER BY name
`

func (q *Queries) ListShops(ctx context.Context) ([]Shop, error) {
	rows, err := q.db.Query(ctx, listShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shop
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerName,
			&i.Phone,
			&i.Area,
			&i.OpeningBalance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShop = `-- name: UpdateShop :one
UPDATE shops
SET name = $2, owner_name = $3, phone = $4, area = $5
WHERE id = $1
RETURNING id, name, owner_name, phone, area, opening_balance, created_at
`

type UpdateShopParams struct {
	ID        int32
	Name      string
	OwnerName pgtype.Text
	Phone     pgtype.Text
	Area      pgtype.Text
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, updateShop,
		arg.ID,
		arg.Name,
		arg.OwnerName,
		arg.Phone,
		arg.Area,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerName,
		&i.Phone,
		&i.Area,
		&i.OpeningBalance,
		&i.CreatedAt,
	)
	return i, err
}
