// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storefront_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStorefrontSettings = `-- name: GetStorefrontSettings :one
SELECT company_id, enabled, cod_enabled, contact_enabled, contact_phone, updated_at FROM company_storefront_settings WHERE company_id = $1
`

func (q *Queries) GetStorefrontSettings(ctx context.Context, companyID int32) (CompanyStorefrontSetting, error) {
	row := q.db.QueryRow(ctx, getStorefrontSettings, companyID)
	var i CompanyStorefrontSetting
	err := row.Scan(
		&i.CompanyID,
		&i.Enabled,
		&i.CodEnabled,
		&i.ContactEnabled,
		&i.ContactPhone,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStorefrontSettings = `-- name: UpsertStorefrontSettings :one
INSERT INTO company_storefront_settings (company_id, enabled, cod_enabled, contact_enabled, contact_phone, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (company_id) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    cod_enabled = EXCLUDED.cod_enabled,
    contact_enabled = EXCLUDED.contact_enabled,
    contact_phone = EXCLUDED.contact_phone,
    updated_at = now()
RETURNING company_id, enabled, cod_enabled, contact_enabled, contact_phone, updated_at
`

type UpsertStorefrontSettingsParams struct {
	CompanyID      int32
	Enabled        bool
	CodEnabled     bool
	ContactEnabled bool
	ContactPhone   pgtype.Text
}

func (q *Queries) UpsertStorefrontSettings(ctx context.Context, arg UpsertStorefrontSettingsParams) (CompanyStorefrontSetting, error) {
	row := q.db.QueryRow(ctx, upsertStorefrontSettings,
		arg.CompanyID,
		arg.Enabled,
		arg.CodEnabled,
		arg.ContactEnabled,
		arg.ContactPhone,
	)
	var i CompanyStorefrontSetting
	err := row.Scan(
		&i.CompanyID,
		&i.Enabled,
		&i.CodEnabled,
		&i.ContactEnabled,
		&i.ContactPhone,
		&i.UpdatedAt,
	)
	return i, err
}
