// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (company_id, subscription_type, start_date, expiry_date, amount, purchase_date, status, granted_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company_id, subscription_type, start_date, expiry_date, amount, purchase_date, status, granted_by, created_on, modified_on, version
`

type CreateSubscriptionParams struct {
	CompanyID        int32
	SubscriptionType string
	StartDate        pgtype.Date
	ExpiryDate       pgtype.Date
	Amount           pgtype.Numeric
	PurchaseDate     pgtype.Date
	Status           string
	GrantedBy        pgtype.Int4
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.CompanyID,
		arg.SubscriptionType,
		arg.StartDate,
		arg.ExpiryDate,
		arg.Amount,
		arg.PurchaseDate,
		arg.Status,
		arg.GrantedBy,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SubscriptionType,
		&i.StartDate,
		&i.ExpiryDate,
		&i.Amount,
		&i.PurchaseDate,
		&i.Status,
		&i.GrantedBy,
		&i.CreatedOn,
		&i.ModifiedOn,
		&i.Version,
	)
	return i, err
}

const getLatestSubscriptionByCompany = `-- name: GetLatestSubscriptionByCompany :one
SELECT id, company_id, subscription_type, start_date, expiry_date, amount, purchase_date, status, granted_by, created_on, modified_on, version FROM subscriptions WHERE company_id = $1 ORDER BY expiry_date DESC, id DESC LIMIT 1
`

func (q *Queries) GetLatestSubscriptionByCompany(ctx context.Context, companyID int32) (Subscription, error) {
	row := q.db.QueryRow(ctx, getLatestSubscriptionByCompany, companyID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SubscriptionType,
		&i.StartDate,
		&i.ExpiryDate,
		&i.Amount,
		&i.PurchaseDate,
		&i.Status,
		&i.GrantedBy,
		&i.CreatedOn,
		&i.ModifiedOn,
		&i.Version,
	)
	return i, err
}

const listSubscriptionsByCompany = `-- name: ListSubscriptionsByCompany :many
SELECT id, company_id, subscription_type, start_date, expiry_date, amount, purchase_date, status, granted_by, created_on, modified_on, version FROM subscriptions WHERE company_id = $1 ORDER BY expiry_date DESC, id DESC
`

func (q *Queries) ListSubscriptionsByCompany(ctx context.Context, companyID int32) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SubscriptionType,
			&i.StartDate,
			&i.ExpiryDate,
			&i.Amount,
			&i.PurchaseDate,
			&i.Status,
			&i.GrantedBy,
			&i.CreatedOn,
			&i.ModifiedOn,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriptionExpiry = `-- name: UpdateSubscriptionExpiry :one
UPDATE subscriptions
SET expiry_date = $2, status = $3, modified_on = now()
WHERE id = $1
RETURNING id, company_id, subscription_type, start_date, expiry_date, amount, purchase_date, status, granted_by, created_on, modified_on, version
`

type UpdateSubscriptionExpiryParams struct {
	ID         int32
	ExpiryDate pgtype.Date
	Status     string
}

func (q *Queries) UpdateSubscriptionExpiry(ctx context.Context, arg UpdateSubscriptionExpiryParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionExpiry, arg.ID, arg.ExpiryDate, arg.Status)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SubscriptionType,
		&i.StartDate,
		&i.ExpiryDate,
		&i.Amount,
		&i.PurchaseDate,
		&i.Status,
		&i.GrantedBy,
		&i.CreatedOn,
		&i.ModifiedOn,
		&i.Version,
	)
	return i, err
}
