// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package db

import (
	"context"
)

const getUnit = `-- name: GetUnit :one
SELECT code, label FROM units WHERE code = $1
`

func (q *Queries) GetUnit(ctx context.Context, code string) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnit, code)
	var i Unit
	err := row.Scan(&i.Code, &i.Label)
	return i, err
}

const listUnits = `-- name: ListUnits :many
SELECT code, label FROM units ORDER BY code
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(&i.Code, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
